/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search;

import com.microsoft.rest.RestClient;

/**
 * The interface for BingECommerceSearch class.
 */
public interface BingECommerceSearch {
    /**
     * Gets the REST client.
     *
     * @return the {@link RestClient} object.
    */
    RestClient restClient();

    /**
     * The default base URL.
     */
    String DEFAULT_BASE_URL = "https://www.bingapis.com/api/v1/retail/search";

    /**
     * Gets the Searchs object to access its operations.
     * @return the Searchs object.
     */
    Searchs searchs();

}
