/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The BoolCondition model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = BoolCondition.class)
@JsonTypeName("BoolCondition")
public class BoolCondition extends EquivalenceConditionBase {
    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private Boolean value;

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public Boolean value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the BoolCondition object itself.
     */
    public BoolCondition withValue(Boolean value) {
        this.value = value;
        return this;
    }

}

