/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ECommerceSearchResponse model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ECommerceSearchResponse.class)
@JsonTypeName("SearchResponse")
public class ECommerceSearchResponse extends ResponseTask {
    /**
     * The impressionId property.
     */
    @JsonProperty(value = "impressionId")
    private String impressionId;

    /**
     * The queryContext property.
     */
    @JsonProperty(value = "queryContext")
    private ResponseQueryContext queryContext;

    /**
     * The items property.
     */
    @JsonProperty(value = "items")
    private ResponseItemsBase items;

    /**
     * The aggregations property.
     */
    @JsonProperty(value = "aggregations")
    private List<ResponseAggregation> aggregations;

    /**
     * The redirectUrl property.
     */
    @JsonProperty(value = "redirectUrl")
    private String redirectUrl;

    /**
     * The customization property.
     */
    @JsonProperty(value = "customization")
    private ResponseCustomization customization;

    /**
     * Get the impressionId value.
     *
     * @return the impressionId value
     */
    public String impressionId() {
        return this.impressionId;
    }

    /**
     * Set the impressionId value.
     *
     * @param impressionId the impressionId value to set
     * @return the ECommerceSearchResponse object itself.
     */
    public ECommerceSearchResponse withImpressionId(String impressionId) {
        this.impressionId = impressionId;
        return this;
    }

    /**
     * Get the queryContext value.
     *
     * @return the queryContext value
     */
    public ResponseQueryContext queryContext() {
        return this.queryContext;
    }

    /**
     * Set the queryContext value.
     *
     * @param queryContext the queryContext value to set
     * @return the ECommerceSearchResponse object itself.
     */
    public ECommerceSearchResponse withQueryContext(ResponseQueryContext queryContext) {
        this.queryContext = queryContext;
        return this;
    }

    /**
     * Get the items value.
     *
     * @return the items value
     */
    public ResponseItemsBase items() {
        return this.items;
    }

    /**
     * Set the items value.
     *
     * @param items the items value to set
     * @return the ECommerceSearchResponse object itself.
     */
    public ECommerceSearchResponse withItems(ResponseItemsBase items) {
        this.items = items;
        return this;
    }

    /**
     * Get the aggregations value.
     *
     * @return the aggregations value
     */
    public List<ResponseAggregation> aggregations() {
        return this.aggregations;
    }

    /**
     * Set the aggregations value.
     *
     * @param aggregations the aggregations value to set
     * @return the ECommerceSearchResponse object itself.
     */
    public ECommerceSearchResponse withAggregations(List<ResponseAggregation> aggregations) {
        this.aggregations = aggregations;
        return this;
    }

    /**
     * Get the redirectUrl value.
     *
     * @return the redirectUrl value
     */
    public String redirectUrl() {
        return this.redirectUrl;
    }

    /**
     * Set the redirectUrl value.
     *
     * @param redirectUrl the redirectUrl value to set
     * @return the ECommerceSearchResponse object itself.
     */
    public ECommerceSearchResponse withRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
        return this;
    }

    /**
     * Get the customization value.
     *
     * @return the customization value
     */
    public ResponseCustomization customization() {
        return this.customization;
    }

    /**
     * Set the customization value.
     *
     * @param customization the customization value to set
     * @return the ECommerceSearchResponse object itself.
     */
    public ECommerceSearchResponse withCustomization(ResponseCustomization customization) {
        this.customization = customization;
        return this;
    }

}

