/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The EquivalenceConditionBase model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = EquivalenceConditionBase.class)
@JsonTypeName("EquivalenceConditionBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "StringCondition", value = StringCondition.class),
    @JsonSubTypes.Type(name = "BoolCondition", value = BoolCondition.class)
})
public class EquivalenceConditionBase extends FieldConditionBase {
    /**
     * Possible values include: 'Eq', 'Ne'.
     */
    @JsonProperty(value = "operator")
    private EquivalenceOperator operator;

    /**
     * Get possible values include: 'Eq', 'Ne'.
     *
     * @return the operator value
     */
    public EquivalenceOperator operator() {
        return this.operator;
    }

    /**
     * Set possible values include: 'Eq', 'Ne'.
     *
     * @param operator the operator value to set
     * @return the EquivalenceConditionBase object itself.
     */
    public EquivalenceConditionBase withOperator(EquivalenceOperator operator) {
        this.operator = operator;
        return this;
    }

}

