/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The GeoCondition model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = GeoCondition.class)
@JsonTypeName("GeoCondition")
public class GeoCondition extends ConditionBase {
    /**
     * The boundary property.
     */
    @JsonProperty(value = "boundary")
    private GeoBoundaryBase boundary;

    /**
     * Get the boundary value.
     *
     * @return the boundary value
     */
    public GeoBoundaryBase boundary() {
        return this.boundary;
    }

    /**
     * Set the boundary value.
     *
     * @param boundary the boundary value to set
     * @return the GeoCondition object itself.
     */
    public GeoCondition withBoundary(GeoBoundaryBase boundary) {
        this.boundary = boundary;
        return this;
    }

}

