/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The GeoDistance model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = GeoDistance.class)
@JsonTypeName("GeoDistance")
public class GeoDistance extends GeoBoundaryBase {
    /**
     * The center property.
     */
    @JsonProperty(value = "center")
    private GeoPoint center;

    /**
     * The radius property.
     */
    @JsonProperty(value = "radius")
    private Double radius;

    /**
     * Get the center value.
     *
     * @return the center value
     */
    public GeoPoint center() {
        return this.center;
    }

    /**
     * Set the center value.
     *
     * @param center the center value to set
     * @return the GeoDistance object itself.
     */
    public GeoDistance withCenter(GeoPoint center) {
        this.center = center;
        return this;
    }

    /**
     * Get the radius value.
     *
     * @return the radius value
     */
    public Double radius() {
        return this.radius;
    }

    /**
     * Set the radius value.
     *
     * @param radius the radius value to set
     * @return the GeoDistance object itself.
     */
    public GeoDistance withRadius(Double radius) {
        this.radius = radius;
        return this;
    }

}

