/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The GeoPoint model.
 */
public class GeoPoint {
    /**
     * The lat property.
     */
    @JsonProperty(value = "lat")
    private Double lat;

    /**
     * The lon property.
     */
    @JsonProperty(value = "lon")
    private Double lon;

    /**
     * Get the lat value.
     *
     * @return the lat value
     */
    public Double lat() {
        return this.lat;
    }

    /**
     * Set the lat value.
     *
     * @param lat the lat value to set
     * @return the GeoPoint object itself.
     */
    public GeoPoint withLat(Double lat) {
        this.lat = lat;
        return this;
    }

    /**
     * Get the lon value.
     *
     * @return the lon value
     */
    public Double lon() {
        return this.lon;
    }

    /**
     * Set the lon value.
     *
     * @param lon the lon value to set
     * @return the GeoPoint object itself.
     */
    public GeoPoint withLon(Double lon) {
        this.lon = lon;
        return this;
    }

}
