/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The RequestFilter model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestFilter.class)
@JsonTypeName("Filter")
public class RequestFilter extends RequestAggregationBase {
    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private ConditionBase value;

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public ConditionBase value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the RequestFilter object itself.
     */
    public RequestFilter withValue(ConditionBase value) {
        this.value = value;
        return this;
    }

}

