/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The RequestRangeFacet model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestRangeFacet.class)
@JsonTypeName("RangeFacet")
public class RequestRangeFacet extends RequestFacetBase {
    /**
     * The interval property.
     */
    @JsonProperty(value = "interval")
    private Integer interval;

    /**
     * Get the interval value.
     *
     * @return the interval value
     */
    public Integer interval() {
        return this.interval;
    }

    /**
     * Set the interval value.
     *
     * @param interval the interval value to set
     * @return the RequestRangeFacet object itself.
     */
    public RequestRangeFacet withInterval(Integer interval) {
        this.interval = interval;
        return this;
    }

}

