/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The RequestMatch model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestMatch.class)
@JsonTypeName("Match")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "MatchStreams", value = RequestBingMatchStreams.class)
})
public class RequestMatch extends RequestQueryClauseBase {
    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the RequestMatch object itself.
     */
    public RequestMatch withValue(String value) {
        this.value = value;
        return this;
    }

}

