/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The RequestDiscoverFacets model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestDiscoverFacets.class)
@JsonTypeName("DiscoverFacets")
public class RequestDiscoverFacets extends RequestAggregationBase {
    /**
     * The discoverFilter property.
     */
    @JsonProperty(value = "discoverFilter")
    private Boolean discoverFilter;

    /**
     * The refinements property.
     */
    @JsonProperty(value = "refinements")
    private Boolean refinements;

    /**
     * The pin property.
     */
    @JsonProperty(value = "pin")
    private List<RequestFacetBase> pin;

    /**
     * The include property.
     */
    @JsonProperty(value = "include")
    private List<RequestFacetBase> include;

    /**
     * The exclude property.
     */
    @JsonProperty(value = "exclude")
    private List<String> exclude;

    /**
     * The facetDefaults property.
     */
    @JsonProperty(value = "facetDefaults")
    private RequestFacet facetDefaults;

    /**
     * The rangeFacetDefaults property.
     */
    @JsonProperty(value = "rangeFacetDefaults")
    private RequestRangeFacet rangeFacetDefaults;

    /**
     * Get the discoverFilter value.
     *
     * @return the discoverFilter value
     */
    public Boolean discoverFilter() {
        return this.discoverFilter;
    }

    /**
     * Set the discoverFilter value.
     *
     * @param discoverFilter the discoverFilter value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withDiscoverFilter(Boolean discoverFilter) {
        this.discoverFilter = discoverFilter;
        return this;
    }

    /**
     * Get the refinements value.
     *
     * @return the refinements value
     */
    public Boolean refinements() {
        return this.refinements;
    }

    /**
     * Set the refinements value.
     *
     * @param refinements the refinements value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withRefinements(Boolean refinements) {
        this.refinements = refinements;
        return this;
    }

    /**
     * Get the pin value.
     *
     * @return the pin value
     */
    public List<RequestFacetBase> pin() {
        return this.pin;
    }

    /**
     * Set the pin value.
     *
     * @param pin the pin value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withPin(List<RequestFacetBase> pin) {
        this.pin = pin;
        return this;
    }

    /**
     * Get the include value.
     *
     * @return the include value
     */
    public List<RequestFacetBase> include() {
        return this.include;
    }

    /**
     * Set the include value.
     *
     * @param include the include value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withInclude(List<RequestFacetBase> include) {
        this.include = include;
        return this;
    }

    /**
     * Get the exclude value.
     *
     * @return the exclude value
     */
    public List<String> exclude() {
        return this.exclude;
    }

    /**
     * Set the exclude value.
     *
     * @param exclude the exclude value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withExclude(List<String> exclude) {
        this.exclude = exclude;
        return this;
    }

    /**
     * Get the facetDefaults value.
     *
     * @return the facetDefaults value
     */
    public RequestFacet facetDefaults() {
        return this.facetDefaults;
    }

    /**
     * Set the facetDefaults value.
     *
     * @param facetDefaults the facetDefaults value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withFacetDefaults(RequestFacet facetDefaults) {
        this.facetDefaults = facetDefaults;
        return this;
    }

    /**
     * Get the rangeFacetDefaults value.
     *
     * @return the rangeFacetDefaults value
     */
    public RequestRangeFacet rangeFacetDefaults() {
        return this.rangeFacetDefaults;
    }

    /**
     * Set the rangeFacetDefaults value.
     *
     * @param rangeFacetDefaults the rangeFacetDefaults value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withRangeFacetDefaults(RequestRangeFacet rangeFacetDefaults) {
        this.rangeFacetDefaults = rangeFacetDefaults;
        return this;
    }

}

