/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The RequestBoostExpression model.
 */
public class RequestBoostExpression {
    /**
     * The condition property.
     */
    @JsonProperty(value = "condition")
    private ConditionBase condition;

    /**
     * The boost property.
     */
    @JsonProperty(value = "boost")
    private Double boost;

    /**
     * Get the condition value.
     *
     * @return the condition value
     */
    public ConditionBase condition() {
        return this.condition;
    }

    /**
     * Set the condition value.
     *
     * @param condition the condition value to set
     * @return the RequestBoostExpression object itself.
     */
    public RequestBoostExpression withCondition(ConditionBase condition) {
        this.condition = condition;
        return this;
    }

    /**
     * Get the boost value.
     *
     * @return the boost value
     */
    public Double boost() {
        return this.boost;
    }

    /**
     * Set the boost value.
     *
     * @param boost the boost value to set
     * @return the RequestBoostExpression object itself.
     */
    public RequestBoostExpression withBoost(Double boost) {
        this.boost = boost;
        return this;
    }

}
