/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The RequestQueryClauseBlock model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestQueryClauseBlock.class)
@JsonTypeName("QueryClauseBlock")
public class RequestQueryClauseBlock extends RequestQueryClauseBase {
    /**
     * The values property.
     */
    @JsonProperty(value = "values")
    private List<RequestQueryClauseBase> values;

    /**
     * Get the values value.
     *
     * @return the values value
     */
    public List<RequestQueryClauseBase> values() {
        return this.values;
    }

    /**
     * Set the values value.
     *
     * @param values the values value to set
     * @return the RequestQueryClauseBlock object itself.
     */
    public RequestQueryClauseBlock withValues(List<RequestQueryClauseBase> values) {
        this.values = values;
        return this;
    }

}

