/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The RequestQueryClauseBase model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestQueryClauseBase.class)
@JsonTypeName("Request.QueryClauseBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "Match", value = RequestMatch.class),
    @JsonSubTypes.Type(name = "QueryClauseBlock", value = RequestQueryClauseBlock.class),
    @JsonSubTypes.Type(name = "LocationMatch", value = RequestLocationMatch.class)
})
public class RequestQueryClauseBase {
}

