/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ResponseCustomization model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseCustomization.class)
@JsonTypeName("Response.Customization")
public class ResponseCustomization extends ResponseTask {
    /**
     * The queryAlteration property.
     */
    @JsonProperty(value = "queryAlteration")
    private Boolean queryAlteration;

    /**
     * The synonyms property.
     */
    @JsonProperty(value = "synonyms")
    private List<Synonym> synonyms;

    /**
     * The rules property.
     */
    @JsonProperty(value = "rules")
    private List<String> rules;

    /**
     * The filter property.
     */
    @JsonProperty(value = "filter")
    private ConditionBase filter;

    /**
     * The boosts property.
     */
    @JsonProperty(value = "boosts")
    private List<ResponseBoostExpression> boosts;

    /**
     * Get the queryAlteration value.
     *
     * @return the queryAlteration value
     */
    public Boolean queryAlteration() {
        return this.queryAlteration;
    }

    /**
     * Set the queryAlteration value.
     *
     * @param queryAlteration the queryAlteration value to set
     * @return the ResponseCustomization object itself.
     */
    public ResponseCustomization withQueryAlteration(Boolean queryAlteration) {
        this.queryAlteration = queryAlteration;
        return this;
    }

    /**
     * Get the synonyms value.
     *
     * @return the synonyms value
     */
    public List<Synonym> synonyms() {
        return this.synonyms;
    }

    /**
     * Set the synonyms value.
     *
     * @param synonyms the synonyms value to set
     * @return the ResponseCustomization object itself.
     */
    public ResponseCustomization withSynonyms(List<Synonym> synonyms) {
        this.synonyms = synonyms;
        return this;
    }

    /**
     * Get the rules value.
     *
     * @return the rules value
     */
    public List<String> rules() {
        return this.rules;
    }

    /**
     * Set the rules value.
     *
     * @param rules the rules value to set
     * @return the ResponseCustomization object itself.
     */
    public ResponseCustomization withRules(List<String> rules) {
        this.rules = rules;
        return this;
    }

    /**
     * Get the filter value.
     *
     * @return the filter value
     */
    public ConditionBase filter() {
        return this.filter;
    }

    /**
     * Set the filter value.
     *
     * @param filter the filter value to set
     * @return the ResponseCustomization object itself.
     */
    public ResponseCustomization withFilter(ConditionBase filter) {
        this.filter = filter;
        return this;
    }

    /**
     * Get the boosts value.
     *
     * @return the boosts value
     */
    public List<ResponseBoostExpression> boosts() {
        return this.boosts;
    }

    /**
     * Set the boosts value.
     *
     * @param boosts the boosts value to set
     * @return the ResponseCustomization object itself.
     */
    public ResponseCustomization withBoosts(List<ResponseBoostExpression> boosts) {
        this.boosts = boosts;
        return this;
    }

}

