/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The ResponseRefinementBase model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseRefinementBase.class)
@JsonTypeName("Response.RefinementBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "RangeRefinement", value = ResponseRangeRefinement.class),
    @JsonSubTypes.Type(name = "NumberRefinement", value = ResponseNumberRefinement.class),
    @JsonSubTypes.Type(name = "StringRefinement", value = ResponseStringRefinement.class),
    @JsonSubTypes.Type(name = "BoolRefinement", value = ResponseBoolRefinement.class)
})
public class ResponseRefinementBase extends ResponseAggregation {
    /**
     * The label property.
     */
    @JsonProperty(value = "label")
    private String label;

    /**
     * Get the label value.
     *
     * @return the label value
     */
    public String label() {
        return this.label;
    }

    /**
     * Set the label value.
     *
     * @param label the label value to set
     * @return the ResponseRefinementBase object itself.
     */
    public ResponseRefinementBase withLabel(String label) {
        this.label = label;
        return this;
    }

}

