/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The ResponseAggregation model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseAggregation.class)
@JsonTypeName("Aggregation")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "Filter", value = ResponseFilter.class),
    @JsonSubTypes.Type(name = "DiscoveredFacets", value = ResponseDiscoveredFacets.class),
    @JsonSubTypes.Type(name = "Response.RefinementBase", value = ResponseRefinementBase.class),
    @JsonSubTypes.Type(name = "Response.FieldAggregationBase", value = ResponseFieldAggregationBase.class)
})
public class ResponseAggregation extends ResponseTask {
    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The estimatedCount property.
     */
    @JsonProperty(value = "estimatedCount")
    private Long estimatedCount;

    /**
     * The aggregations property.
     */
    @JsonProperty(value = "aggregations")
    private List<ResponseAggregation> aggregations;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the ResponseAggregation object itself.
     */
    public ResponseAggregation withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the estimatedCount value.
     *
     * @return the estimatedCount value
     */
    public Long estimatedCount() {
        return this.estimatedCount;
    }

    /**
     * Set the estimatedCount value.
     *
     * @param estimatedCount the estimatedCount value to set
     * @return the ResponseAggregation object itself.
     */
    public ResponseAggregation withEstimatedCount(Long estimatedCount) {
        this.estimatedCount = estimatedCount;
        return this;
    }

    /**
     * Get the aggregations value.
     *
     * @return the aggregations value
     */
    public List<ResponseAggregation> aggregations() {
        return this.aggregations;
    }

    /**
     * Set the aggregations value.
     *
     * @param aggregations the aggregations value to set
     * @return the ResponseAggregation object itself.
     */
    public ResponseAggregation withAggregations(List<ResponseAggregation> aggregations) {
        this.aggregations = aggregations;
        return this;
    }

}

