/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ResponseQueryContext model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseQueryContext.class)
@JsonTypeName("Response.QueryContext")
public class ResponseQueryContext extends ResponseTask {
    /**
     * The originalQuery property.
     */
    @JsonProperty(value = "originalQuery")
    private String originalQuery;

    /**
     * The alteredQuery property.
     */
    @JsonProperty(value = "alteredQuery")
    private String alteredQuery;

    /**
     * Get the originalQuery value.
     *
     * @return the originalQuery value
     */
    public String originalQuery() {
        return this.originalQuery;
    }

    /**
     * Set the originalQuery value.
     *
     * @param originalQuery the originalQuery value to set
     * @return the ResponseQueryContext object itself.
     */
    public ResponseQueryContext withOriginalQuery(String originalQuery) {
        this.originalQuery = originalQuery;
        return this;
    }

    /**
     * Get the alteredQuery value.
     *
     * @return the alteredQuery value
     */
    public String alteredQuery() {
        return this.alteredQuery;
    }

    /**
     * Set the alteredQuery value.
     *
     * @param alteredQuery the alteredQuery value to set
     * @return the ResponseQueryContext object itself.
     */
    public ResponseQueryContext withAlteredQuery(String alteredQuery) {
        this.alteredQuery = alteredQuery;
        return this;
    }

}

