/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ResponseItems model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseItems.class)
@JsonTypeName("Items")
public class ResponseItems extends ResponseItemsBase {
    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private List<ResponseItem> value;

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public List<ResponseItem> value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the ResponseItems object itself.
     */
    public ResponseItems withValue(List<ResponseItem> value) {
        this.value = value;
        return this;
    }

}

