/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The ResponseItemsBase model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseItemsBase.class)
@JsonTypeName("Response.ItemsBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "Items", value = ResponseItems.class)
})
public class ResponseItemsBase extends ResponseTask {
    /**
     * The totalEstimatedMatches property.
     */
    @JsonProperty(value = "totalEstimatedMatches")
    private Long totalEstimatedMatches;

    /**
     * Get the totalEstimatedMatches value.
     *
     * @return the totalEstimatedMatches value
     */
    public Long totalEstimatedMatches() {
        return this.totalEstimatedMatches;
    }

    /**
     * Set the totalEstimatedMatches value.
     *
     * @param totalEstimatedMatches the totalEstimatedMatches value to set
     * @return the ResponseItemsBase object itself.
     */
    public ResponseItemsBase withTotalEstimatedMatches(Long totalEstimatedMatches) {
        this.totalEstimatedMatches = totalEstimatedMatches;
        return this;
    }

}

