/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ResponseRangeRefinement model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseRangeRefinement.class)
@JsonTypeName("RangeRefinement")
public class ResponseRangeRefinement extends ResponseRefinementBase {
    /**
     * The ge property.
     */
    @JsonProperty(value = "ge")
    private Double ge;

    /**
     * The lt property.
     */
    @JsonProperty(value = "lt")
    private Double lt;

    /**
     * Get the ge value.
     *
     * @return the ge value
     */
    public Double ge() {
        return this.ge;
    }

    /**
     * Set the ge value.
     *
     * @param ge the ge value to set
     * @return the ResponseRangeRefinement object itself.
     */
    public ResponseRangeRefinement withGe(Double ge) {
        this.ge = ge;
        return this;
    }

    /**
     * Get the lt value.
     *
     * @return the lt value
     */
    public Double lt() {
        return this.lt;
    }

    /**
     * Set the lt value.
     *
     * @param lt the lt value to set
     * @return the ResponseRangeRefinement object itself.
     */
    public ResponseRangeRefinement withLt(Double lt) {
        this.lt = lt;
        return this;
    }

}

