/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ResponseStringFacet model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseStringFacet.class)
@JsonTypeName("StringFacet")
public class ResponseStringFacet extends ResponseFacetBase {
    /**
     * The refinements property.
     */
    @JsonProperty(value = "refinements")
    private List<ResponseStringRefinement> refinements;

    /**
     * Get the refinements value.
     *
     * @return the refinements value
     */
    public List<ResponseStringRefinement> refinements() {
        return this.refinements;
    }

    /**
     * Set the refinements value.
     *
     * @param refinements the refinements value to set
     * @return the ResponseStringFacet object itself.
     */
    public ResponseStringFacet withRefinements(List<ResponseStringRefinement> refinements) {
        this.refinements = refinements;
        return this;
    }

}

