/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The StringSetCondition model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = StringSetCondition.class)
@JsonTypeName("StringSetCondition")
public class StringSetCondition extends SetConditionBase {
    /**
     * The values property.
     */
    @JsonProperty(value = "values")
    private List<String> values;

    /**
     * Get the values value.
     *
     * @return the values value
     */
    public List<String> values() {
        return this.values;
    }

    /**
     * Set the values value.
     *
     * @param values the values value to set
     * @return the StringSetCondition object itself.
     */
    public StringSetCondition withValues(List<String> values) {
        this.values = values;
        return this;
    }

}

