// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A response containing the status for a request to delete documents from the
 * index.
 */
public class DeleteDocumentsResponse {
    /**
     * The status for the document deletion request. Possible values include:
     * 'Succeeded', 'PartiallySucceeded', 'Failed'.
     */
    @JsonProperty(value = "status")
    private String status;

    /**
     * An aggregation of error messages for errors that happened while
     * processing the request, if any.
     */
    @JsonProperty(value = "errorMessage")
    private String errorMessage;

    /**
     * A list of status results per document.
     */
    @JsonProperty(value = "result")
    private List<ResponseDocumentDeletionResult> result;

    /**
     * Get the status for the document deletion request. Possible values include: 'Succeeded', 'PartiallySucceeded', 'Failed'.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set the status for the document deletion request. Possible values include: 'Succeeded', 'PartiallySucceeded', 'Failed'.
     *
     * @param status the status value to set
     * @return the DeleteDocumentsResponse object itself.
     */
    public DeleteDocumentsResponse withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get an aggregation of error messages for errors that happened while processing the request, if any.
     *
     * @return the errorMessage value
     */
    public String errorMessage() {
        return this.errorMessage;
    }

    /**
     * Set an aggregation of error messages for errors that happened while processing the request, if any.
     *
     * @param errorMessage the errorMessage value to set
     * @return the DeleteDocumentsResponse object itself.
     */
    public DeleteDocumentsResponse withErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

    /**
     * Get a list of status results per document.
     *
     * @return the result value
     */
    public List<ResponseDocumentDeletionResult> result() {
        return this.result;
    }

    /**
     * Set a list of status results per document.
     *
     * @param result the result value to set
     * @return the DeleteDocumentsResponse object itself.
     */
    public DeleteDocumentsResponse withResult(List<ResponseDocumentDeletionResult> result) {
        this.result = result;
        return this;
    }

}
