/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A response that represents the status of an index within its supported
 * regions.
 */
public class IndexStatusResponse {
    /**
     * A list of objects containing the status of the index within a region.
     */
    @JsonProperty(value = "indexStatuses")
    private List<ResponseIndexStatus> indexStatuses;

    /**
     * Get a list of objects containing the status of the index within a region.
     *
     * @return the indexStatuses value
     */
    public List<ResponseIndexStatus> indexStatuses() {
        return this.indexStatuses;
    }

    /**
     * Set a list of objects containing the status of the index within a region.
     *
     * @param indexStatuses the indexStatuses value to set
     * @return the IndexStatusResponse object itself.
     */
    public IndexStatusResponse withIndexStatuses(List<ResponseIndexStatus> indexStatuses) {
        this.indexStatuses = indexStatuses;
        return this;
    }

}
