// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * This package contains the models classes for BingCommerceIngestion.
 */
package com.microsoft.bing.commerce.ingestion.models;
