/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A response that represents the status of a push data update given an update
 * id.
 */
public class PushUpdateStatusResponse {
    /**
     * The id that uniquely identifies the push data update.
     */
    @JsonProperty(value = "updateId")
    private String updateId;

    /**
     * The wholistic update status for the push data update. Possible values
     * include: 'InProgress', 'Succeeded', 'PartiallySucceeded', 'Failed'.
     */
    @JsonProperty(value = "status")
    private String status;

    /**
     * The total number of items that are part of the upate.
     */
    @JsonProperty(value = "totalKeys")
    private Integer totalKeys;

    /**
     * The total number of items that have successfully been updated.
     */
    @JsonProperty(value = "successfulKeys")
    private Integer successfulKeys;

    /**
     * An aggregation of any error messages that happened while ingesting any
     * of the records.
     */
    @JsonProperty(value = "failureMessages")
    private List<String> failureMessages;

    /**
     * A drill down for the push update status for each record.
     */
    @JsonProperty(value = "records")
    private List<ResponseRecordStatus> records;

    /**
     * Get the id that uniquely identifies the push data update.
     *
     * @return the updateId value
     */
    public String updateId() {
        return this.updateId;
    }

    /**
     * Set the id that uniquely identifies the push data update.
     *
     * @param updateId the updateId value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withUpdateId(String updateId) {
        this.updateId = updateId;
        return this;
    }

    /**
     * Get the wholistic update status for the push data update. Possible values include: 'InProgress', 'Succeeded', 'PartiallySucceeded', 'Failed'.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set the wholistic update status for the push data update. Possible values include: 'InProgress', 'Succeeded', 'PartiallySucceeded', 'Failed'.
     *
     * @param status the status value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get the total number of items that are part of the upate.
     *
     * @return the totalKeys value
     */
    public Integer totalKeys() {
        return this.totalKeys;
    }

    /**
     * Set the total number of items that are part of the upate.
     *
     * @param totalKeys the totalKeys value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withTotalKeys(Integer totalKeys) {
        this.totalKeys = totalKeys;
        return this;
    }

    /**
     * Get the total number of items that have successfully been updated.
     *
     * @return the successfulKeys value
     */
    public Integer successfulKeys() {
        return this.successfulKeys;
    }

    /**
     * Set the total number of items that have successfully been updated.
     *
     * @param successfulKeys the successfulKeys value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withSuccessfulKeys(Integer successfulKeys) {
        this.successfulKeys = successfulKeys;
        return this;
    }

    /**
     * Get an aggregation of any error messages that happened while ingesting any of the records.
     *
     * @return the failureMessages value
     */
    public List<String> failureMessages() {
        return this.failureMessages;
    }

    /**
     * Set an aggregation of any error messages that happened while ingesting any of the records.
     *
     * @param failureMessages the failureMessages value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withFailureMessages(List<String> failureMessages) {
        this.failureMessages = failureMessages;
        return this;
    }

    /**
     * Get a drill down for the push update status for each record.
     *
     * @return the records value
     */
    public List<ResponseRecordStatus> records() {
        return this.records;
    }

    /**
     * Set a drill down for the push update status for each record.
     *
     * @param records the records value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withRecords(List<ResponseRecordStatus> records) {
        this.records = records;
        return this;
    }

}
