/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines a set of strings.
 */
public class RequestsStringSet {
    /**
     * A set of strings.
     */
    @JsonProperty(value = "values")
    private List<String> values;

    /**
     * Get a set of strings.
     *
     * @return the values value
     */
    public List<String> values() {
        return this.values;
    }

    /**
     * Set a set of strings.
     *
     * @param values the values value to set
     * @return the RequestsStringSet object itself.
     */
    public RequestsStringSet withValues(List<String> values) {
        this.values = values;
        return this;
    }

}
