// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.ingestion.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A response that represents a status to a push data update for a record.
 */
public class ResponseRecordStatus {
    /**
     * The _itemid for the record being updated.
     */
    @JsonProperty(value = "recordId")
    private String recordId;

    /**
     * The status for the push data update regarding the specified item id.
     * Possible values include: 'InProgress', 'Succeeded',
     * 'PartiallySucceeded', 'Failed'.
     */
    @JsonProperty(value = "status")
    private String status;

    /**
     * An optional error message in case of an error while ingesting the
     * record.
     */
    @JsonProperty(value = "errorMessage")
    private String errorMessage;

    /**
     * Get the _itemid for the record being updated.
     *
     * @return the recordId value
     */
    public String recordId() {
        return this.recordId;
    }

    /**
     * Set the _itemid for the record being updated.
     *
     * @param recordId the recordId value to set
     * @return the ResponseRecordStatus object itself.
     */
    public ResponseRecordStatus withRecordId(String recordId) {
        this.recordId = recordId;
        return this;
    }

    /**
     * Get the status for the push data update regarding the specified item id. Possible values include: 'InProgress', 'Succeeded', 'PartiallySucceeded', 'Failed'.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set the status for the push data update regarding the specified item id. Possible values include: 'InProgress', 'Succeeded', 'PartiallySucceeded', 'Failed'.
     *
     * @param status the status value to set
     * @return the ResponseRecordStatus object itself.
     */
    public ResponseRecordStatus withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get an optional error message in case of an error while ingesting the record.
     *
     * @return the errorMessage value
     */
    public String errorMessage() {
        return this.errorMessage;
    }

    /**
     * Set an optional error message in case of an error while ingesting the record.
     *
     * @param errorMessage the errorMessage value to set
     * @return the ResponseRecordStatus object itself.
     */
    public ResponseRecordStatus withErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

}
