/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.ingestion.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A response representing the result of a request to delete a document from
 * your index's catalog.
 */
public class ResponseDocumentDeletionResult {
    /**
     * The _itemid for the item item that has been deleted from the index.
     */
    @JsonProperty(value = "documentId")
    private String documentId;

    /**
     * A boolean flag that specifies whether or not the document has been
     * successfully deleted.
     */
    @JsonProperty(value = "deleted")
    private Boolean deleted;

    /**
     * An error message for the request, if any.
     */
    @JsonProperty(value = "errorMessage")
    private String errorMessage;

    /**
     * Get the _itemid for the item item that has been deleted from the index.
     *
     * @return the documentId value
     */
    public String documentId() {
        return this.documentId;
    }

    /**
     * Set the _itemid for the item item that has been deleted from the index.
     *
     * @param documentId the documentId value to set
     * @return the ResponseDocumentDeletionResult object itself.
     */
    public ResponseDocumentDeletionResult withDocumentId(String documentId) {
        this.documentId = documentId;
        return this;
    }

    /**
     * Get a boolean flag that specifies whether or not the document has been successfully deleted.
     *
     * @return the deleted value
     */
    public Boolean deleted() {
        return this.deleted;
    }

    /**
     * Set a boolean flag that specifies whether or not the document has been successfully deleted.
     *
     * @param deleted the deleted value to set
     * @return the ResponseDocumentDeletionResult object itself.
     */
    public ResponseDocumentDeletionResult withDeleted(Boolean deleted) {
        this.deleted = deleted;
        return this;
    }

    /**
     * Get an error message for the request, if any.
     *
     * @return the errorMessage value
     */
    public String errorMessage() {
        return this.errorMessage;
    }

    /**
     * Set an error message for the request, if any.
     *
     * @param errorMessage the errorMessage value to set
     * @return the ResponseDocumentDeletionResult object itself.
     */
    public ResponseDocumentDeletionResult withErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

}
