/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A response representing the status of a transformation config tryout
 * requset.
 */
public class TransformationTryoutResponse {
    /**
     * The status of the transformation config tryout.
     */
    @JsonProperty(value = "status")
    private String status;

    /**
     * Any error messages that happened while transforming, if any.
     */
    @JsonProperty(value = "errorMessage")
    private String errorMessage;

    /**
     * A list of records that the transformation config outputed.
     */
    @JsonProperty(value = "results")
    private List<String> results;

    /**
     * The console output of the transformation config, if any. Can be useful
     * for debugging.
     */
    @JsonProperty(value = "consoleOutput")
    private List<String> consoleOutput;

    /**
     * Get the status of the transformation config tryout.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set the status of the transformation config tryout.
     *
     * @param status the status value to set
     * @return the TransformationTryoutResponse object itself.
     */
    public TransformationTryoutResponse withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get any error messages that happened while transforming, if any.
     *
     * @return the errorMessage value
     */
    public String errorMessage() {
        return this.errorMessage;
    }

    /**
     * Set any error messages that happened while transforming, if any.
     *
     * @param errorMessage the errorMessage value to set
     * @return the TransformationTryoutResponse object itself.
     */
    public TransformationTryoutResponse withErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

    /**
     * Get a list of records that the transformation config outputed.
     *
     * @return the results value
     */
    public List<String> results() {
        return this.results;
    }

    /**
     * Set a list of records that the transformation config outputed.
     *
     * @param results the results value to set
     * @return the TransformationTryoutResponse object itself.
     */
    public TransformationTryoutResponse withResults(List<String> results) {
        this.results = results;
        return this;
    }

    /**
     * Get the console output of the transformation config, if any. Can be useful for debugging.
     *
     * @return the consoleOutput value
     */
    public List<String> consoleOutput() {
        return this.consoleOutput;
    }

    /**
     * Set the console output of the transformation config, if any. Can be useful for debugging.
     *
     * @param consoleOutput the consoleOutput value to set
     * @return the TransformationTryoutResponse object itself.
     */
    public TransformationTryoutResponse withConsoleOutput(List<String> consoleOutput) {
        this.consoleOutput = consoleOutput;
        return this;
    }

}
