/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.implementation;

import com.microsoft.bing.ecommerce.search.BingECommerceSearch;
import com.microsoft.bing.ecommerce.search.Searchs;
import com.microsoft.rest.ServiceClient;
import com.microsoft.rest.RestClient;
import okhttp3.OkHttpClient;
import retrofit2.Retrofit;

/**
 * Initializes a new instance of the BingECommerceSearch class.
 */
public class BingECommerceSearchImpl extends ServiceClient implements BingECommerceSearch {

    /**
     * The Searchs object to access its operations.
     */
    private Searchs searchs;

    /**
     * Gets the Searchs object to access its operations.
     * @return the Searchs object.
     */
    public Searchs searchs() {
        return this.searchs;
    }

    /**
     * Initializes an instance of BingECommerceSearch client.
     */
    public BingECommerceSearchImpl() {
        this("https://www.bingapis.com/api/v1/retail/search");
    }

    /**
     * Initializes an instance of BingECommerceSearch client.
     *
     * @param baseUrl the base URL of the host
     */
    public BingECommerceSearchImpl(String baseUrl) {
        super(baseUrl);
        initialize();
    }

    /**
     * Initializes an instance of BingECommerceSearch client.
     *
     * @param clientBuilder the builder for building an OkHttp client, bundled with user configurations
     * @param restBuilder the builder for building an Retrofit client, bundled with user configurations
     */
    public BingECommerceSearchImpl(OkHttpClient.Builder clientBuilder, Retrofit.Builder restBuilder) {
        this("https://www.bingapis.com/api/v1/retail/search", clientBuilder, restBuilder);
        initialize();
    }

    /**
     * Initializes an instance of BingECommerceSearch client.
     *
     * @param baseUrl the base URL of the host
     * @param clientBuilder the builder for building an OkHttp client, bundled with user configurations
     * @param restBuilder the builder for building an Retrofit client, bundled with user configurations
     */
    public BingECommerceSearchImpl(String baseUrl, OkHttpClient.Builder clientBuilder, Retrofit.Builder restBuilder) {
        super(baseUrl, clientBuilder, restBuilder);
        initialize();
    }

    /**
     * Initializes an instance of BingECommerceSearch client.
     *
     * @param restClient the REST client containing pre-configured settings
     */
    public BingECommerceSearchImpl(RestClient restClient) {
        super(restClient);
        initialize();
    }

    private void initialize() {
        this.searchs = new SearchsImpl(retrofit(), this);
    }
}
