/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.search.implementation;

import retrofit2.Retrofit;
import com.microsoft.bing.ecommerce.search.Searchs;
import com.google.common.reflect.TypeToken;
import com.microsoft.bing.ecommerce.search.models.ECommerceSearchPostRequest;
import com.microsoft.bing.ecommerce.search.models.ECommerceSearchResponse;
import com.microsoft.rest.RestException;
import com.microsoft.rest.ServiceCallback;
import com.microsoft.rest.ServiceFuture;
import com.microsoft.rest.ServiceResponse;
import com.microsoft.rest.Validator;
import java.io.IOException;
import okhttp3.ResponseBody;
import retrofit2.http.Body;
import retrofit2.http.GET;
import retrofit2.http.Headers;
import retrofit2.http.Path;
import retrofit2.http.POST;
import retrofit2.http.Query;
import retrofit2.Response;
import rx.functions.Func1;
import rx.Observable;

/**
 * An instance of this class provides access to all the operations defined
 * in Searchs.
 */
public class SearchsImpl implements Searchs {
    /** The Retrofit service to perform REST calls. */
    private SearchsService service;
    /** The service client containing this operation class. */
    private BingECommerceSearchImpl client;

    /**
     * Initializes an instance of Searchs.
     *
     * @param retrofit the Retrofit instance built from a Retrofit Builder.
     * @param client the instance of the service client containing this operation class.
     */
    public SearchsImpl(Retrofit retrofit, BingECommerceSearchImpl client) {
        this.service = retrofit.create(SearchsService.class);
        this.client = client;
    }

    /**
     * The interface defining all the services for Searchs to be
     * used by Retrofit to perform actually REST calls.
     */
    interface SearchsService {
        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.bing.ecommerce.search.Searchs post" })
        @POST("{tenant}/indexes/{index}")
        Observable<Response<ResponseBody>> post(@Path("tenant") String tenant, @Path("index") String index, @Body ECommerceSearchPostRequest body);

        @Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.bing.ecommerce.search.Searchs get" })
        @GET("{tenant}/indexes/{index}")
        Observable<Response<ResponseBody>> get(@Path("tenant") String tenant, @Path("index") String index, @Query("mkt") String mkt, @Query("setlang") String setlang, @Query("q") String q, @Query("select") String select, @Query("orderby") String orderby, @Query("top") Integer top, @Query("skip") Integer skip, @Query("discoverfacets") Boolean discoverfacets, @Query("alteration") Boolean alteration, @Query("debug") Boolean debug, @Query("searchinstanceid") String searchinstanceid);

    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws RestException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the ECommerceSearchResponse object if successful.
     */
    public ECommerceSearchResponse post(String tenant, String index) {
        return postWithServiceResponseAsync(tenant, index).toBlocking().single().body();
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<ECommerceSearchResponse> postAsync(String tenant, String index, final ServiceCallback<ECommerceSearchResponse> serviceCallback) {
        return ServiceFuture.fromResponse(postWithServiceResponseAsync(tenant, index), serviceCallback);
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ECommerceSearchResponse object
     */
    public Observable<ECommerceSearchResponse> postAsync(String tenant, String index) {
        return postWithServiceResponseAsync(tenant, index).map(new Func1<ServiceResponse<ECommerceSearchResponse>, ECommerceSearchResponse>() {
            @Override
            public ECommerceSearchResponse call(ServiceResponse<ECommerceSearchResponse> response) {
                return response.body();
            }
        });
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ECommerceSearchResponse object
     */
    public Observable<ServiceResponse<ECommerceSearchResponse>> postWithServiceResponseAsync(String tenant, String index) {
        if (tenant == null) {
            throw new IllegalArgumentException("Parameter tenant is required and cannot be null.");
        }
        if (index == null) {
            throw new IllegalArgumentException("Parameter index is required and cannot be null.");
        }
        final ECommerceSearchPostRequest body = null;
        return service.post(tenant, index, body)
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<ECommerceSearchResponse>>>() {
                @Override
                public Observable<ServiceResponse<ECommerceSearchResponse>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<ECommerceSearchResponse> clientResponse = postDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @param body the ECommerceSearchPostRequest value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws RestException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the ECommerceSearchResponse object if successful.
     */
    public ECommerceSearchResponse post(String tenant, String index, ECommerceSearchPostRequest body) {
        return postWithServiceResponseAsync(tenant, index, body).toBlocking().single().body();
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @param body the ECommerceSearchPostRequest value
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<ECommerceSearchResponse> postAsync(String tenant, String index, ECommerceSearchPostRequest body, final ServiceCallback<ECommerceSearchResponse> serviceCallback) {
        return ServiceFuture.fromResponse(postWithServiceResponseAsync(tenant, index, body), serviceCallback);
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @param body the ECommerceSearchPostRequest value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ECommerceSearchResponse object
     */
    public Observable<ECommerceSearchResponse> postAsync(String tenant, String index, ECommerceSearchPostRequest body) {
        return postWithServiceResponseAsync(tenant, index, body).map(new Func1<ServiceResponse<ECommerceSearchResponse>, ECommerceSearchResponse>() {
            @Override
            public ECommerceSearchResponse call(ServiceResponse<ECommerceSearchResponse> response) {
                return response.body();
            }
        });
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @param body the ECommerceSearchPostRequest value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ECommerceSearchResponse object
     */
    public Observable<ServiceResponse<ECommerceSearchResponse>> postWithServiceResponseAsync(String tenant, String index, ECommerceSearchPostRequest body) {
        if (tenant == null) {
            throw new IllegalArgumentException("Parameter tenant is required and cannot be null.");
        }
        if (index == null) {
            throw new IllegalArgumentException("Parameter index is required and cannot be null.");
        }
        Validator.validate(body);
        return service.post(tenant, index, body)
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<ECommerceSearchResponse>>>() {
                @Override
                public Observable<ServiceResponse<ECommerceSearchResponse>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<ECommerceSearchResponse> clientResponse = postDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<ECommerceSearchResponse> postDelegate(Response<ResponseBody> response) throws RestException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<ECommerceSearchResponse, RestException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<ECommerceSearchResponse>() { }.getType())
                .build(response);
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws RestException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the ECommerceSearchResponse object if successful.
     */
    public ECommerceSearchResponse get(String tenant, String index) {
        return getWithServiceResponseAsync(tenant, index).toBlocking().single().body();
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<ECommerceSearchResponse> getAsync(String tenant, String index, final ServiceCallback<ECommerceSearchResponse> serviceCallback) {
        return ServiceFuture.fromResponse(getWithServiceResponseAsync(tenant, index), serviceCallback);
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ECommerceSearchResponse object
     */
    public Observable<ECommerceSearchResponse> getAsync(String tenant, String index) {
        return getWithServiceResponseAsync(tenant, index).map(new Func1<ServiceResponse<ECommerceSearchResponse>, ECommerceSearchResponse>() {
            @Override
            public ECommerceSearchResponse call(ServiceResponse<ECommerceSearchResponse> response) {
                return response.body();
            }
        });
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ECommerceSearchResponse object
     */
    public Observable<ServiceResponse<ECommerceSearchResponse>> getWithServiceResponseAsync(String tenant, String index) {
        if (tenant == null) {
            throw new IllegalArgumentException("Parameter tenant is required and cannot be null.");
        }
        if (index == null) {
            throw new IllegalArgumentException("Parameter index is required and cannot be null.");
        }
        final String mkt = null;
        final String setlang = null;
        final String q = null;
        final String select = null;
        final String orderby = null;
        final Integer top = null;
        final Integer skip = null;
        final Boolean discoverfacets = null;
        final Boolean alteration = null;
        final Boolean debug = null;
        final String searchinstanceid = null;
        return service.get(tenant, index, mkt, setlang, q, select, orderby, top, skip, discoverfacets, alteration, debug, searchinstanceid)
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<ECommerceSearchResponse>>>() {
                @Override
                public Observable<ServiceResponse<ECommerceSearchResponse>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<ECommerceSearchResponse> clientResponse = getDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @param mkt the String value
     * @param setlang the String value
     * @param q the String value
     * @param select the String value
     * @param orderby the String value
     * @param top the Integer value
     * @param skip the Integer value
     * @param discoverfacets the Boolean value
     * @param alteration the Boolean value
     * @param debug the Boolean value
     * @param searchinstanceid the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @throws RestException thrown if the request is rejected by server
     * @throws RuntimeException all other wrapped checked exceptions if the request fails to be sent
     * @return the ECommerceSearchResponse object if successful.
     */
    public ECommerceSearchResponse get(String tenant, String index, String mkt, String setlang, String q, String select, String orderby, Integer top, Integer skip, Boolean discoverfacets, Boolean alteration, Boolean debug, String searchinstanceid) {
        return getWithServiceResponseAsync(tenant, index, mkt, setlang, q, select, orderby, top, skip, discoverfacets, alteration, debug, searchinstanceid).toBlocking().single().body();
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @param mkt the String value
     * @param setlang the String value
     * @param q the String value
     * @param select the String value
     * @param orderby the String value
     * @param top the Integer value
     * @param skip the Integer value
     * @param discoverfacets the Boolean value
     * @param alteration the Boolean value
     * @param debug the Boolean value
     * @param searchinstanceid the String value
     * @param serviceCallback the async ServiceCallback to handle successful and failed responses.
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the {@link ServiceFuture} object
     */
    public ServiceFuture<ECommerceSearchResponse> getAsync(String tenant, String index, String mkt, String setlang, String q, String select, String orderby, Integer top, Integer skip, Boolean discoverfacets, Boolean alteration, Boolean debug, String searchinstanceid, final ServiceCallback<ECommerceSearchResponse> serviceCallback) {
        return ServiceFuture.fromResponse(getWithServiceResponseAsync(tenant, index, mkt, setlang, q, select, orderby, top, skip, discoverfacets, alteration, debug, searchinstanceid), serviceCallback);
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @param mkt the String value
     * @param setlang the String value
     * @param q the String value
     * @param select the String value
     * @param orderby the String value
     * @param top the Integer value
     * @param skip the Integer value
     * @param discoverfacets the Boolean value
     * @param alteration the Boolean value
     * @param debug the Boolean value
     * @param searchinstanceid the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ECommerceSearchResponse object
     */
    public Observable<ECommerceSearchResponse> getAsync(String tenant, String index, String mkt, String setlang, String q, String select, String orderby, Integer top, Integer skip, Boolean discoverfacets, Boolean alteration, Boolean debug, String searchinstanceid) {
        return getWithServiceResponseAsync(tenant, index, mkt, setlang, q, select, orderby, top, skip, discoverfacets, alteration, debug, searchinstanceid).map(new Func1<ServiceResponse<ECommerceSearchResponse>, ECommerceSearchResponse>() {
            @Override
            public ECommerceSearchResponse call(ServiceResponse<ECommerceSearchResponse> response) {
                return response.body();
            }
        });
    }

    /**
     *
     * @param tenant the String value
     * @param index the String value
     * @param mkt the String value
     * @param setlang the String value
     * @param q the String value
     * @param select the String value
     * @param orderby the String value
     * @param top the Integer value
     * @param skip the Integer value
     * @param discoverfacets the Boolean value
     * @param alteration the Boolean value
     * @param debug the Boolean value
     * @param searchinstanceid the String value
     * @throws IllegalArgumentException thrown if parameters fail the validation
     * @return the observable to the ECommerceSearchResponse object
     */
    public Observable<ServiceResponse<ECommerceSearchResponse>> getWithServiceResponseAsync(String tenant, String index, String mkt, String setlang, String q, String select, String orderby, Integer top, Integer skip, Boolean discoverfacets, Boolean alteration, Boolean debug, String searchinstanceid) {
        if (tenant == null) {
            throw new IllegalArgumentException("Parameter tenant is required and cannot be null.");
        }
        if (index == null) {
            throw new IllegalArgumentException("Parameter index is required and cannot be null.");
        }
        return service.get(tenant, index, mkt, setlang, q, select, orderby, top, skip, discoverfacets, alteration, debug, searchinstanceid)
            .flatMap(new Func1<Response<ResponseBody>, Observable<ServiceResponse<ECommerceSearchResponse>>>() {
                @Override
                public Observable<ServiceResponse<ECommerceSearchResponse>> call(Response<ResponseBody> response) {
                    try {
                        ServiceResponse<ECommerceSearchResponse> clientResponse = getDelegate(response);
                        return Observable.just(clientResponse);
                    } catch (Throwable t) {
                        return Observable.error(t);
                    }
                }
            });
    }

    private ServiceResponse<ECommerceSearchResponse> getDelegate(Response<ResponseBody> response) throws RestException, IOException, IllegalArgumentException {
        return this.client.restClient().responseBuilderFactory().<ECommerceSearchResponse, RestException>newInstance(this.client.serializerAdapter())
                .register(200, new TypeToken<ECommerceSearchResponse>() { }.getType())
                .build(response);
    }

}
