// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for CategoryOperator.
 */
public enum CategoryOperator {
    /** Enum value In. */
    IN("In"),

    /** Enum value NotIn. */
    NOT_IN("NotIn");

    /** The actual serialized value for a CategoryOperator instance. */
    private String value;

    CategoryOperator(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a CategoryOperator instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed CategoryOperator object, or null if unable to parse.
     */
    @JsonCreator
    public static CategoryOperator fromString(String value) {
        CategoryOperator[] items = CategoryOperator.values();
        for (CategoryOperator item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
