// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The response to a Bing Commerce Search Query.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = CommerceSearchResponse.class)
@JsonTypeName("SearchResponse")
public class CommerceSearchResponse extends ResponseTask {
    /**
     * A random GUID to uniquely track the search response.
     */
    @JsonProperty(value = "impressionId")
    private String impressionId;

    /**
     * The query alteration result.
     */
    @JsonProperty(value = "queryContext")
    private ResponseQueryContext queryContext;

    /**
     * The item results.
     */
    @JsonProperty(value = "items")
    private ResponseItemsBase items;

    /**
     * The aggregations result.
     */
    @JsonProperty(value = "aggregations")
    private List<ResponseAggregation> aggregations;

    /**
     * The redirect url for this the current query from the request search
     * instance.
     */
    @JsonProperty(value = "redirectUrl")
    private String redirectUrl;

    /**
     * The user defined customizations applied the search query.
     */
    @JsonProperty(value = "customization")
    private ResponseCustomization customization;

    /**
     * Get a random GUID to uniquely track the search response.
     *
     * @return the impressionId value
     */
    public String impressionId() {
        return this.impressionId;
    }

    /**
     * Set a random GUID to uniquely track the search response.
     *
     * @param impressionId the impressionId value to set
     * @return the CommerceSearchResponse object itself.
     */
    public CommerceSearchResponse withImpressionId(String impressionId) {
        this.impressionId = impressionId;
        return this;
    }

    /**
     * Get the query alteration result.
     *
     * @return the queryContext value
     */
    public ResponseQueryContext queryContext() {
        return this.queryContext;
    }

    /**
     * Set the query alteration result.
     *
     * @param queryContext the queryContext value to set
     * @return the CommerceSearchResponse object itself.
     */
    public CommerceSearchResponse withQueryContext(ResponseQueryContext queryContext) {
        this.queryContext = queryContext;
        return this;
    }

    /**
     * Get the item results.
     *
     * @return the items value
     */
    public ResponseItemsBase items() {
        return this.items;
    }

    /**
     * Set the item results.
     *
     * @param items the items value to set
     * @return the CommerceSearchResponse object itself.
     */
    public CommerceSearchResponse withItems(ResponseItemsBase items) {
        this.items = items;
        return this;
    }

    /**
     * Get the aggregations result.
     *
     * @return the aggregations value
     */
    public List<ResponseAggregation> aggregations() {
        return this.aggregations;
    }

    /**
     * Set the aggregations result.
     *
     * @param aggregations the aggregations value to set
     * @return the CommerceSearchResponse object itself.
     */
    public CommerceSearchResponse withAggregations(List<ResponseAggregation> aggregations) {
        this.aggregations = aggregations;
        return this;
    }

    /**
     * Get the redirect url for this the current query from the request search instance.
     *
     * @return the redirectUrl value
     */
    public String redirectUrl() {
        return this.redirectUrl;
    }

    /**
     * Set the redirect url for this the current query from the request search instance.
     *
     * @param redirectUrl the redirectUrl value to set
     * @return the CommerceSearchResponse object itself.
     */
    public CommerceSearchResponse withRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
        return this;
    }

    /**
     * Get the user defined customizations applied the search query.
     *
     * @return the customization value
     */
    public ResponseCustomization customization() {
        return this.customization;
    }

    /**
     * Set the user defined customizations applied the search query.
     *
     * @param customization the customization value to set
     * @return the CommerceSearchResponse object itself.
     */
    public CommerceSearchResponse withCustomization(ResponseCustomization customization) {
        this.customization = customization;
        return this;
    }

}

