/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The condition that triggered a boost in ranking score.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ConditionBase.class)
@JsonTypeName("ConditionBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "ConditionBlock", value = ConditionBlock.class),
    @JsonSubTypes.Type(name = "FieldConditionBase", value = FieldConditionBase.class),
    @JsonSubTypes.Type(name = "GeoCondition", value = GeoCondition.class)
})
public class ConditionBase {
}

