/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * Defines the abstract base type for conditions with a field name.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = FieldConditionBase.class)
@JsonTypeName("FieldConditionBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "EquivalenceConditionBase", value = EquivalenceConditionBase.class),
    @JsonSubTypes.Type(name = "NumericCondition", value = NumericCondition.class),
    @JsonSubTypes.Type(name = "CategoryCondition", value = CategoryCondition.class),
    @JsonSubTypes.Type(name = "SetConditionBase", value = SetConditionBase.class)
})
public class FieldConditionBase extends ConditionBase {
    /**
     * The name of the field.
     */
    @JsonProperty(value = "field")
    private String field;

    /**
     * Get the name of the field.
     *
     * @return the field value
     */
    public String field() {
        return this.field;
    }

    /**
     * Set the name of the field.
     *
     * @param field the field value to set
     * @return the FieldConditionBase object itself.
     */
    public FieldConditionBase withField(String field) {
        this.field = field;
        return this;
    }

}

