/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines a geographical box to match the results that lie within it.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = GeoBoundingBox.class)
@JsonTypeName("GeoBoundingBox")
public class GeoBoundingBox extends GeoBoundaryBase {
    /**
     * The top-left corner geo-location of the box.
     */
    @JsonProperty(value = "topLeft")
    private GeoPoint topLeft;

    /**
     * The bottom-right corner geo-location of the box.
     */
    @JsonProperty(value = "bottomRight")
    private GeoPoint bottomRight;

    /**
     * Get the top-left corner geo-location of the box.
     *
     * @return the topLeft value
     */
    public GeoPoint topLeft() {
        return this.topLeft;
    }

    /**
     * Set the top-left corner geo-location of the box.
     *
     * @param topLeft the topLeft value to set
     * @return the GeoBoundingBox object itself.
     */
    public GeoBoundingBox withTopLeft(GeoPoint topLeft) {
        this.topLeft = topLeft;
        return this;
    }

    /**
     * Get the bottom-right corner geo-location of the box.
     *
     * @return the bottomRight value
     */
    public GeoPoint bottomRight() {
        return this.bottomRight;
    }

    /**
     * Set the bottom-right corner geo-location of the box.
     *
     * @param bottomRight the bottomRight value to set
     * @return the GeoBoundingBox object itself.
     */
    public GeoBoundingBox withBottomRight(GeoPoint bottomRight) {
        this.bottomRight = bottomRight;
        return this;
    }

}

