/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines a condition that applies on a geo-location field. It can appear in a
 * filter, a boost, or a filter aggregation.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = GeoCondition.class)
@JsonTypeName("GeoCondition")
public class GeoCondition extends ConditionBase {
    /**
     * The geo-bondary to match the results against.
     */
    @JsonProperty(value = "boundary")
    private GeoBoundaryBase boundary;

    /**
     * Get the geo-bondary to match the results against.
     *
     * @return the boundary value
     */
    public GeoBoundaryBase boundary() {
        return this.boundary;
    }

    /**
     * Set the geo-bondary to match the results against.
     *
     * @param boundary the boundary value to set
     * @return the GeoCondition object itself.
     */
    public GeoCondition withBoundary(GeoBoundaryBase boundary) {
        this.boundary = boundary;
        return this;
    }

}

