// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines a geographical boundary that matches location within a certain
 * euclidean distance from a point.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = GeoDistance.class)
@JsonTypeName("GeoDistance")
public class GeoDistance extends GeoBoundaryBase {
    /**
     * The geo-location for the center point to match around.
     */
    @JsonProperty(value = "center")
    private GeoPoint center;

    /**
     * The accpeptable euclidean distance to the center.
     */
    @JsonProperty(value = "radius")
    private Double radius;

    /**
     * Get the geo-location for the center point to match around.
     *
     * @return the center value
     */
    public GeoPoint center() {
        return this.center;
    }

    /**
     * Set the geo-location for the center point to match around.
     *
     * @param center the center value to set
     * @return the GeoDistance object itself.
     */
    public GeoDistance withCenter(GeoPoint center) {
        this.center = center;
        return this;
    }

    /**
     * Get the accpeptable euclidean distance to the center.
     *
     * @return the radius value
     */
    public Double radius() {
        return this.radius;
    }

    /**
     * Set the accpeptable euclidean distance to the center.
     *
     * @param radius the radius value to set
     * @return the GeoDistance object itself.
     */
    public GeoDistance withRadius(Double radius) {
        this.radius = radius;
        return this;
    }

}

