// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * Defines the abstract base type for an aggregation request.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestAggregationBase.class)
@JsonTypeName("Request.AggregationBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "Filter", value = RequestFilter.class),
    @JsonSubTypes.Type(name = "Request.FieldAggregationBase", value = RequestFieldAggregationBase.class),
    @JsonSubTypes.Type(name = "DiscoverFacets", value = RequestDiscoverFacets.class)
})
public class RequestAggregationBase {
    /**
     * A label that you specify for your aggregations, which the API passes
     * through and returns with the response.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * A list of child aggregations.
     */
    @JsonProperty(value = "aggregations")
    private List<RequestAggregationBase> aggregations;

    /**
     * Get a label that you specify for your aggregations, which the API passes through and returns with the response.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set a label that you specify for your aggregations, which the API passes through and returns with the response.
     *
     * @param name the name value to set
     * @return the RequestAggregationBase object itself.
     */
    public RequestAggregationBase withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get a list of child aggregations.
     *
     * @return the aggregations value
     */
    public List<RequestAggregationBase> aggregations() {
        return this.aggregations;
    }

    /**
     * Set a list of child aggregations.
     *
     * @param aggregations the aggregations value to set
     * @return the RequestAggregationBase object itself.
     */
    public RequestAggregationBase withAggregations(List<RequestAggregationBase> aggregations) {
        this.aggregations = aggregations;
        return this;
    }

}

