/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines user location to match. If an explicit location is specified in a
 * match query, this is ignored.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestLocationMatch.class)
@JsonTypeName("LocationMatch")
public class RequestLocationMatch extends RequestQueryClauseBase {
    /**
     * The geo-location that you wish for the search to be applied around.
     */
    @JsonProperty(value = "center")
    private GeoPoint center;

    /**
     * The accuracy of the search on that location in meters.
     */
    @JsonProperty(value = "radius")
    private Double radius;

    /**
     * Get the geo-location that you wish for the search to be applied around.
     *
     * @return the center value
     */
    public GeoPoint center() {
        return this.center;
    }

    /**
     * Set the geo-location that you wish for the search to be applied around.
     *
     * @param center the center value to set
     * @return the RequestLocationMatch object itself.
     */
    public RequestLocationMatch withCenter(GeoPoint center) {
        this.center = center;
        return this;
    }

    /**
     * Get the accuracy of the search on that location in meters.
     *
     * @return the radius value
     */
    public Double radius() {
        return this.radius;
    }

    /**
     * Set the accuracy of the search on that location in meters.
     *
     * @param radius the radius value to set
     * @return the RequestLocationMatch object itself.
     */
    public RequestLocationMatch withRadius(Double radius) {
        this.radius = radius;
        return this;
    }

}

