/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The RequestClientId model.
 */
public class RequestClientId {
    /**
     * Possible values include: 'MUID', 'UID'.
     */
    @JsonProperty(value = "kind")
    private String kind;

    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Get possible values include: 'MUID', 'UID'.
     *
     * @return the kind value
     */
    public String kind() {
        return this.kind;
    }

    /**
     * Set possible values include: 'MUID', 'UID'.
     *
     * @param kind the kind value to set
     * @return the RequestClientId object itself.
     */
    public RequestClientId withKind(String kind) {
        this.kind = kind;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the RequestClientId object itself.
     */
    public RequestClientId withValue(String value) {
        this.value = value;
        return this;
    }

}
