/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines how to return items from the result set.
 */
public class RequestItems {
    /**
     * A list of fields that should appear for each item of the response.
     */
    @JsonProperty(value = "select")
    private List<String> select;

    /**
     * A comma-separated list of OData order syntax expressions.
     */
    @JsonProperty(value = "orderBy")
    private String orderBy;

    /**
     * The number of results to return. It can be used for pagination.
     */
    @JsonProperty(value = "top")
    private Integer top;

    /**
     * The number of results to skip in the result set. Supports pagination.
     */
    @JsonProperty(value = "skip")
    private Integer skip;

    /**
     * A boolean to specify whether you want the result set to exclude
     * duplicates. Default is `false`.
     */
    @JsonProperty(value = "dedupe")
    private Boolean dedupe;

    /**
     * Get a list of fields that should appear for each item of the response.
     *
     * @return the select value
     */
    public List<String> select() {
        return this.select;
    }

    /**
     * Set a list of fields that should appear for each item of the response.
     *
     * @param select the select value to set
     * @return the RequestItems object itself.
     */
    public RequestItems withSelect(List<String> select) {
        this.select = select;
        return this;
    }

    /**
     * Get a comma-separated list of OData order syntax expressions.
     *
     * @return the orderBy value
     */
    public String orderBy() {
        return this.orderBy;
    }

    /**
     * Set a comma-separated list of OData order syntax expressions.
     *
     * @param orderBy the orderBy value to set
     * @return the RequestItems object itself.
     */
    public RequestItems withOrderBy(String orderBy) {
        this.orderBy = orderBy;
        return this;
    }

    /**
     * Get the number of results to return. It can be used for pagination.
     *
     * @return the top value
     */
    public Integer top() {
        return this.top;
    }

    /**
     * Set the number of results to return. It can be used for pagination.
     *
     * @param top the top value to set
     * @return the RequestItems object itself.
     */
    public RequestItems withTop(Integer top) {
        this.top = top;
        return this;
    }

    /**
     * Get the number of results to skip in the result set. Supports pagination.
     *
     * @return the skip value
     */
    public Integer skip() {
        return this.skip;
    }

    /**
     * Set the number of results to skip in the result set. Supports pagination.
     *
     * @param skip the skip value to set
     * @return the RequestItems object itself.
     */
    public RequestItems withSkip(Integer skip) {
        this.skip = skip;
        return this;
    }

    /**
     * Get a boolean to specify whether you want the result set to exclude duplicates. Default is `false`.
     *
     * @return the dedupe value
     */
    public Boolean dedupe() {
        return this.dedupe;
    }

    /**
     * Set a boolean to specify whether you want the result set to exclude duplicates. Default is `false`.
     *
     * @param dedupe the dedupe value to set
     * @return the RequestItems object itself.
     */
    public RequestItems withDedupe(Boolean dedupe) {
        this.dedupe = dedupe;
        return this;
    }

}
