/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines a facet with refinements that have numerical ranges.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestRangeFacet.class)
@JsonTypeName("RangeFacet")
public class RequestRangeFacet extends RequestFacetBase {
    /**
     * Defines the size of the interval that can be used to refine a search
     * which utilizes numerical range faceting.
     */
    @JsonProperty(value = "interval")
    private Integer interval;

    /**
     * Get defines the size of the interval that can be used to refine a search which utilizes numerical range faceting.
     *
     * @return the interval value
     */
    public Integer interval() {
        return this.interval;
    }

    /**
     * Set defines the size of the interval that can be used to refine a search which utilizes numerical range faceting.
     *
     * @param interval the interval value to set
     * @return the RequestRangeFacet object itself.
     */
    public RequestRangeFacet withInterval(Integer interval) {
        this.interval = interval;
        return this;
    }

}

