/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * Defines the abstract base type for an aggregation request that have a field.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestFieldAggregationBase.class)
@JsonTypeName("Request.FieldAggregationBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "Request.FacetBase", value = RequestFacetBase.class),
    @JsonSubTypes.Type(name = "Min", value = RequestMin.class),
    @JsonSubTypes.Type(name = "Max", value = RequestMax.class)
})
public class RequestFieldAggregationBase extends RequestAggregationBase {
    /**
     * The field name.
     */
    @JsonProperty(value = "field")
    private String field;

    /**
     * Get the field name.
     *
     * @return the field value
     */
    public String field() {
        return this.field;
    }

    /**
     * Set the field name.
     *
     * @param field the field value to set
     * @return the RequestFieldAggregationBase object itself.
     */
    public RequestFieldAggregationBase withField(String field) {
        this.field = field;
        return this;
    }

}

