/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines a filter aggregation.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestFilter.class)
@JsonTypeName("Filter")
public class RequestFilter extends RequestAggregationBase {
    /**
     * The condition to match for the aggregation.
     */
    @JsonProperty(value = "value")
    private ConditionBase value;

    /**
     * The includeCustomizations property.
     */
    @JsonProperty(value = "includeCustomizations")
    private Boolean includeCustomizations;

    /**
     * Get the condition to match for the aggregation.
     *
     * @return the value value
     */
    public ConditionBase value() {
        return this.value;
    }

    /**
     * Set the condition to match for the aggregation.
     *
     * @param value the value value to set
     * @return the RequestFilter object itself.
     */
    public RequestFilter withValue(ConditionBase value) {
        this.value = value;
        return this;
    }

    /**
     * Get the includeCustomizations value.
     *
     * @return the includeCustomizations value
     */
    public Boolean includeCustomizations() {
        return this.includeCustomizations;
    }

    /**
     * Set the includeCustomizations value.
     *
     * @param includeCustomizations the includeCustomizations value to set
     * @return the RequestFilter object itself.
     */
    public RequestFilter withIncludeCustomizations(Boolean includeCustomizations) {
        this.includeCustomizations = includeCustomizations;
        return this;
    }

}

