/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines an object that contains the result of query alteration.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseQueryContext.class)
@JsonTypeName("Response.QueryContext")
public class ResponseQueryContext extends ResponseTask {
    /**
     * The user's query string as entered.
     */
    @JsonProperty(value = "originalQuery")
    private String originalQuery;

    /**
     * The altered query string that the API actually uses for the query (for
     * example, corrected spelling).
     */
    @JsonProperty(value = "alteredQuery")
    private String alteredQuery;

    /**
     * Get the user's query string as entered.
     *
     * @return the originalQuery value
     */
    public String originalQuery() {
        return this.originalQuery;
    }

    /**
     * Set the user's query string as entered.
     *
     * @param originalQuery the originalQuery value to set
     * @return the ResponseQueryContext object itself.
     */
    public ResponseQueryContext withOriginalQuery(String originalQuery) {
        this.originalQuery = originalQuery;
        return this;
    }

    /**
     * Get the altered query string that the API actually uses for the query (for example, corrected spelling).
     *
     * @return the alteredQuery value
     */
    public String alteredQuery() {
        return this.alteredQuery;
    }

    /**
     * Set the altered query string that the API actually uses for the query (for example, corrected spelling).
     *
     * @param alteredQuery the alteredQuery value to set
     * @return the ResponseQueryContext object itself.
     */
    public ResponseQueryContext withAlteredQuery(String alteredQuery) {
        this.alteredQuery = alteredQuery;
        return this;
    }

}

