/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The ResponseTask model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseTask.class)
@JsonTypeName("Response.Task")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "Response.QueryContext", value = ResponseQueryContext.class),
    @JsonSubTypes.Type(name = "Response.ItemsBase", value = ResponseItemsBase.class),
    @JsonSubTypes.Type(name = "Aggregation", value = ResponseAggregation.class),
    @JsonSubTypes.Type(name = "Response.Customization", value = ResponseCustomization.class),
    @JsonSubTypes.Type(name = "SearchResponse", value = CommerceSearchResponse.class)
})
public class ResponseTask {
    /**
     * A list of errors that happened to the task, if any.
     */
    @JsonProperty(value = "errors")
    private List<ResponseError> errors;

    /**
     * The debug property.
     */
    @JsonProperty(value = "debug")
    private List<ResponseDebugInfo> debug;

    /**
     * Get a list of errors that happened to the task, if any.
     *
     * @return the errors value
     */
    public List<ResponseError> errors() {
        return this.errors;
    }

    /**
     * Set a list of errors that happened to the task, if any.
     *
     * @param errors the errors value to set
     * @return the ResponseTask object itself.
     */
    public ResponseTask withErrors(List<ResponseError> errors) {
        this.errors = errors;
        return this;
    }

    /**
     * Get the debug value.
     *
     * @return the debug value
     */
    public List<ResponseDebugInfo> debug() {
        return this.debug;
    }

    /**
     * Set the debug value.
     *
     * @param debug the debug value to set
     * @return the ResponseTask object itself.
     */
    public ResponseTask withDebug(List<ResponseDebugInfo> debug) {
        this.debug = debug;
        return this;
    }

}

