// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines a range facet refinement on a numeric field.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseRangeRefinement.class)
@JsonTypeName("RangeRefinement")
public class ResponseRangeRefinement extends ResponseRefinementBase {
    /**
     * The inclusive lower bound of the range. Values in the refinement are
     * greater than or equal to this lower bound.
     */
    @JsonProperty(value = "ge")
    private Double ge;

    /**
     * The exclusive upper bound of the range. Values in the refinement are
     * strictly less than this upper bound.
     */
    @JsonProperty(value = "lt")
    private Double lt;

    /**
     * Get the inclusive lower bound of the range. Values in the refinement are greater than or equal to this lower bound.
     *
     * @return the ge value
     */
    public Double ge() {
        return this.ge;
    }

    /**
     * Set the inclusive lower bound of the range. Values in the refinement are greater than or equal to this lower bound.
     *
     * @param ge the ge value to set
     * @return the ResponseRangeRefinement object itself.
     */
    public ResponseRangeRefinement withGe(Double ge) {
        this.ge = ge;
        return this;
    }

    /**
     * Get the exclusive upper bound of the range. Values in the refinement are strictly less than this upper bound.
     *
     * @return the lt value
     */
    public Double lt() {
        return this.lt;
    }

    /**
     * Set the exclusive upper bound of the range. Values in the refinement are strictly less than this upper bound.
     *
     * @param lt the lt value to set
     * @return the ResponseRangeRefinement object itself.
     */
    public ResponseRangeRefinement withLt(Double lt) {
        this.lt = lt;
        return this;
    }

}

