// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines an expression that modifies the ranking score of results based on a
 * condition.
 */
public class ResponseBoostExpression {
    /**
     * The condition that triggered a boost in ranking score.
     */
    @JsonProperty(value = "condition")
    private ConditionBase condition;

    /**
     * The magnitude of a boost applied.
     */
    @JsonProperty(value = "boost")
    private Double boost;

    /**
     * Get the condition that triggered a boost in ranking score.
     *
     * @return the condition value
     */
    public ConditionBase condition() {
        return this.condition;
    }

    /**
     * Set the condition that triggered a boost in ranking score.
     *
     * @param condition the condition value to set
     * @return the ResponseBoostExpression object itself.
     */
    public ResponseBoostExpression withCondition(ConditionBase condition) {
        this.condition = condition;
        return this;
    }

    /**
     * Get the magnitude of a boost applied.
     *
     * @return the boost value
     */
    public Double boost() {
        return this.boost;
    }

    /**
     * Set the magnitude of a boost applied.
     *
     * @param boost the boost value to set
     * @return the ResponseBoostExpression object itself.
     */
    public ResponseBoostExpression withBoost(Double boost) {
        this.boost = boost;
        return this;
    }

}
