// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Returns the minimum value of the field encountered within the match set.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseMin.class)
@JsonTypeName("Min")
public class ResponseMin extends ResponseFieldAggregationBase {
    /**
     * The minimum value of the field for the match set.
     */
    @JsonProperty(value = "value")
    private Double value;

    /**
     * Get the minimum value of the field for the match set.
     *
     * @return the value value
     */
    public Double value() {
        return this.value;
    }

    /**
     * Set the minimum value of the field for the match set.
     *
     * @param value the value value to set
     * @return the ResponseMin object itself.
     */
    public ResponseMin withValue(Double value) {
        this.value = value;
        return this;
    }

}

