/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * The ResponseBingBingItemDebugInfo model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseBingBingItemDebugInfo.class)
@JsonTypeName("BingItemDebugInfo")
public class ResponseBingBingItemDebugInfo extends ResponseDebugInfo {
    /**
     * The perfectMatchingStreams property.
     */
    @JsonProperty(value = "perfectMatchingStreams")
    private List<ResponseBingMatchingStream> perfectMatchingStreams;

    /**
     * The completeMatchingStreams property.
     */
    @JsonProperty(value = "completeMatchingStreams")
    private List<ResponseBingMatchingStream> completeMatchingStreams;

    /**
     * Get the perfectMatchingStreams value.
     *
     * @return the perfectMatchingStreams value
     */
    public List<ResponseBingMatchingStream> perfectMatchingStreams() {
        return this.perfectMatchingStreams;
    }

    /**
     * Set the perfectMatchingStreams value.
     *
     * @param perfectMatchingStreams the perfectMatchingStreams value to set
     * @return the ResponseBingBingItemDebugInfo object itself.
     */
    public ResponseBingBingItemDebugInfo withPerfectMatchingStreams(List<ResponseBingMatchingStream> perfectMatchingStreams) {
        this.perfectMatchingStreams = perfectMatchingStreams;
        return this;
    }

    /**
     * Get the completeMatchingStreams value.
     *
     * @return the completeMatchingStreams value
     */
    public List<ResponseBingMatchingStream> completeMatchingStreams() {
        return this.completeMatchingStreams;
    }

    /**
     * Set the completeMatchingStreams value.
     *
     * @param completeMatchingStreams the completeMatchingStreams value to set
     * @return the ResponseBingBingItemDebugInfo object itself.
     */
    public ResponseBingBingItemDebugInfo withCompleteMatchingStreams(List<ResponseBingMatchingStream> completeMatchingStreams) {
        this.completeMatchingStreams = completeMatchingStreams;
        return this;
    }

}

