/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * Defines a facet refinement on a string field.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseStringRefinement.class)
@JsonTypeName("StringRefinement")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "CategoryRefinement", value = ResponseCategoryRefinement.class)
})
public class ResponseStringRefinement extends ResponseRefinementBase {
    /**
     * The actual filter value used to filter the list of items.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Get the actual filter value used to filter the list of items.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the actual filter value used to filter the list of items.
     *
     * @param value the value value to set
     * @return the ResponseStringRefinement object itself.
     */
    public ResponseStringRefinement withValue(String value) {
        this.value = value;
        return this;
    }

}

