// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines the facets the API determines for you.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseDiscoveredFacets.class)
@JsonTypeName("DiscoveredFacets")
public class ResponseDiscoveredFacets extends ResponseAggregation {
    /**
     * The filter condition that facet discovery was limited to, satisfied by
     * the top results.
     */
    @JsonProperty(value = "filter")
    private ConditionBase filter;

    /**
     * Get the filter condition that facet discovery was limited to, satisfied by the top results.
     *
     * @return the filter value
     */
    public ConditionBase filter() {
        return this.filter;
    }

    /**
     * Set the filter condition that facet discovery was limited to, satisfied by the top results.
     *
     * @param filter the filter value to set
     * @return the ResponseDiscoveredFacets object itself.
     */
    public ResponseDiscoveredFacets withFilter(ConditionBase filter) {
        this.filter = filter;
        return this;
    }

}

