/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Returns the maximum value of the field encountered within the match set.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseMax.class)
@JsonTypeName("Max")
public class ResponseMax extends ResponseFieldAggregationBase {
    /**
     * The maximum value of the field for the match set.
     */
    @JsonProperty(value = "value")
    private Double value;

    /**
     * Get the maximum value of the field for the match set.
     *
     * @return the value value
     */
    public Double value() {
        return this.value;
    }

    /**
     * Set the maximum value of the field for the match set.
     *
     * @param value the value value to set
     * @return the ResponseMax object itself.
     */
    public ResponseMax withValue(Double value) {
        this.value = value;
        return this;
    }

}

