/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines an item from your content catalog.
 */
public class ResponseItem {
    /**
     * The ID of the index the item belongs to.
     */
    @JsonProperty(value = "indexId")
    private String indexId;

    /**
     * An ID that uniquely identifies an item within the index.
     */
    @JsonProperty(value = "itemId")
    private String itemId;

    /**
     * A value that indicates how well the item matches the query. Higher
     * values indicate a closer match.
     */
    @JsonProperty(value = "score")
    private Double score;

    /**
     * An object with the selected fields as properties.
     */
    @JsonProperty(value = "fields")
    private Object fields;

    /**
     * The debug property.
     */
    @JsonProperty(value = "debug")
    private List<ResponseDebugInfo> debug;

    /**
     * Get the ID of the index the item belongs to.
     *
     * @return the indexId value
     */
    public String indexId() {
        return this.indexId;
    }

    /**
     * Set the ID of the index the item belongs to.
     *
     * @param indexId the indexId value to set
     * @return the ResponseItem object itself.
     */
    public ResponseItem withIndexId(String indexId) {
        this.indexId = indexId;
        return this;
    }

    /**
     * Get an ID that uniquely identifies an item within the index.
     *
     * @return the itemId value
     */
    public String itemId() {
        return this.itemId;
    }

    /**
     * Set an ID that uniquely identifies an item within the index.
     *
     * @param itemId the itemId value to set
     * @return the ResponseItem object itself.
     */
    public ResponseItem withItemId(String itemId) {
        this.itemId = itemId;
        return this;
    }

    /**
     * Get a value that indicates how well the item matches the query. Higher values indicate a closer match.
     *
     * @return the score value
     */
    public Double score() {
        return this.score;
    }

    /**
     * Set a value that indicates how well the item matches the query. Higher values indicate a closer match.
     *
     * @param score the score value to set
     * @return the ResponseItem object itself.
     */
    public ResponseItem withScore(Double score) {
        this.score = score;
        return this;
    }

    /**
     * Get an object with the selected fields as properties.
     *
     * @return the fields value
     */
    public Object fields() {
        return this.fields;
    }

    /**
     * Set an object with the selected fields as properties.
     *
     * @param fields the fields value to set
     * @return the ResponseItem object itself.
     */
    public ResponseItem withFields(Object fields) {
        this.fields = fields;
        return this;
    }

    /**
     * Get the debug value.
     *
     * @return the debug value
     */
    public List<ResponseDebugInfo> debug() {
        return this.debug;
    }

    /**
     * Set the debug value.
     *
     * @param debug the debug value to set
     * @return the ResponseItem object itself.
     */
    public ResponseItem withDebug(List<ResponseDebugInfo> debug) {
        this.debug = debug;
        return this;
    }

}
