// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * Defines the abstract base type for item results.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseItemsBase.class)
@JsonTypeName("Response.ItemsBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "Items", value = ResponseItems.class)
})
public class ResponseItemsBase extends ResponseTask {
    /**
     * An estimated count of the items in the full result set.
     */
    @JsonProperty(value = "totalEstimatedMatches")
    private Long totalEstimatedMatches;

    /**
     * Get an estimated count of the items in the full result set.
     *
     * @return the totalEstimatedMatches value
     */
    public Long totalEstimatedMatches() {
        return this.totalEstimatedMatches;
    }

    /**
     * Set an estimated count of the items in the full result set.
     *
     * @param totalEstimatedMatches the totalEstimatedMatches value to set
     * @return the ResponseItemsBase object itself.
     */
    public ResponseItemsBase withTotalEstimatedMatches(Long totalEstimatedMatches) {
        this.totalEstimatedMatches = totalEstimatedMatches;
        return this;
    }

}

