/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines The error details that happened to a task.
 */
public class ResponseError {
    /**
     * Possible values include: 'None', 'ServerError', 'InvalidRequest',
     * 'InsufficientAuthorization'.
     */
    @JsonProperty(value = "code")
    private String code;

    /**
     * Possible values include: 'UnexpectedError', 'ResourceError',
     * 'DeadlineExceeded', 'ParameterMissing', 'ParameterInvalidValue'.
     */
    @JsonProperty(value = "subCode")
    private String subCode;

    /**
     * The message property.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * The moreDetails property.
     */
    @JsonProperty(value = "moreDetails")
    private String moreDetails;

    /**
     * Get possible values include: 'None', 'ServerError', 'InvalidRequest', 'InsufficientAuthorization'.
     *
     * @return the code value
     */
    public String code() {
        return this.code;
    }

    /**
     * Set possible values include: 'None', 'ServerError', 'InvalidRequest', 'InsufficientAuthorization'.
     *
     * @param code the code value to set
     * @return the ResponseError object itself.
     */
    public ResponseError withCode(String code) {
        this.code = code;
        return this;
    }

    /**
     * Get possible values include: 'UnexpectedError', 'ResourceError', 'DeadlineExceeded', 'ParameterMissing', 'ParameterInvalidValue'.
     *
     * @return the subCode value
     */
    public String subCode() {
        return this.subCode;
    }

    /**
     * Set possible values include: 'UnexpectedError', 'ResourceError', 'DeadlineExceeded', 'ParameterMissing', 'ParameterInvalidValue'.
     *
     * @param subCode the subCode value to set
     * @return the ResponseError object itself.
     */
    public ResponseError withSubCode(String subCode) {
        this.subCode = subCode;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the ResponseError object itself.
     */
    public ResponseError withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the moreDetails value.
     *
     * @return the moreDetails value
     */
    public String moreDetails() {
        return this.moreDetails;
    }

    /**
     * Set the moreDetails value.
     *
     * @param moreDetails the moreDetails value to set
     * @return the ResponseError object itself.
     */
    public ResponseError withMoreDetails(String moreDetails) {
        this.moreDetails = moreDetails;
        return this;
    }

}
