/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines an equivalence condition for a string field. It can appear in a
 * filter, a boost, or a filter aggregation.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = StringCondition.class)
@JsonTypeName("StringCondition")
public class StringCondition extends EquivalenceConditionBase {
    /**
     * The value to compare the field against.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * Get the value to compare the field against.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value to compare the field against.
     *
     * @param value the value value to set
     * @return the StringCondition object itself.
     */
    public StringCondition withValue(String value) {
        this.value = value;
        return this;
    }

}

