/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines a set of alternate terms (or phrases) that can be applied to request
 * query.
 */
public class Synonym {
    /**
     * The id for the saved synonym.
     */
    @JsonProperty(value = "synonymId")
    private String synonymId;

    /**
     * The alternate terms to apply.
     */
    @JsonProperty(value = "synonyms")
    private List<String> synonyms;

    /**
     * Get the id for the saved synonym.
     *
     * @return the synonymId value
     */
    public String synonymId() {
        return this.synonymId;
    }

    /**
     * Set the id for the saved synonym.
     *
     * @param synonymId the synonymId value to set
     * @return the Synonym object itself.
     */
    public Synonym withSynonymId(String synonymId) {
        this.synonymId = synonymId;
        return this;
    }

    /**
     * Get the alternate terms to apply.
     *
     * @return the synonyms value
     */
    public List<String> synonyms() {
        return this.synonyms;
    }

    /**
     * Set the alternate terms to apply.
     *
     * @param synonyms the synonyms value to set
     * @return the Synonym object itself.
     */
    public Synonym withSynonyms(List<String> synonyms) {
        this.synonyms = synonyms;
        return this;
    }

}
