// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An expression that modifies the ranking score for item search results
 * satisfying a condition.
 */
public class BoostExpression {
    /**
     * The condition that items must satisfy to be boosted.
     */
    @JsonProperty(value = "condition")
    private ConditionBase condition;

    /**
     * The value to add to the ranking score. The range is -10,000,000 to
     * 10,000,000.
     */
    @JsonProperty(value = "boost")
    private Double boost;

    /**
     * Get the condition that items must satisfy to be boosted.
     *
     * @return the condition value
     */
    public ConditionBase condition() {
        return this.condition;
    }

    /**
     * Set the condition that items must satisfy to be boosted.
     *
     * @param condition the condition value to set
     * @return the BoostExpression object itself.
     */
    public BoostExpression withCondition(ConditionBase condition) {
        this.condition = condition;
        return this;
    }

    /**
     * Get the value to add to the ranking score. The range is -10,000,000 to 10,000,000.
     *
     * @return the boost value
     */
    public Double boost() {
        return this.boost;
    }

    /**
     * Set the value to add to the ranking score. The range is -10,000,000 to 10,000,000.
     *
     * @param boost the boost value to set
     * @return the BoostExpression object itself.
     */
    public BoostExpression withBoost(Double boost) {
        this.boost = boost;
        return this;
    }

}
