// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines a list of composite conditions for filtering and boosting.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ConditionBlock.class)
@JsonTypeName("ConditionBlock")
public class ConditionBlock extends ConditionBase {
    /**
     * The set of operands.
     */
    @JsonProperty(value = "conditions")
    private List<ConditionBase> conditions;

    /**
     * and, or. Default is `And`. Possible values include: 'And', 'Or'.
     */
    @JsonProperty(value = "operator")
    private LogicalOperator operator;

    /**
     * Get the set of operands.
     *
     * @return the conditions value
     */
    public List<ConditionBase> conditions() {
        return this.conditions;
    }

    /**
     * Set the set of operands.
     *
     * @param conditions the conditions value to set
     * @return the ConditionBlock object itself.
     */
    public ConditionBlock withConditions(List<ConditionBase> conditions) {
        this.conditions = conditions;
        return this;
    }

    /**
     * Get and, or. Default is `And`. Possible values include: 'And', 'Or'.
     *
     * @return the operator value
     */
    public LogicalOperator operator() {
        return this.operator;
    }

    /**
     * Set and, or. Default is `And`. Possible values include: 'And', 'Or'.
     *
     * @param operator the operator value to set
     * @return the ConditionBlock object itself.
     */
    public ConditionBlock withOperator(LogicalOperator operator) {
        this.operator = operator;
        return this;
    }

}

