// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines an aggregation type that triggers facet discovery of significant
 * facets.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = RequestDiscoverFacets.class)
@JsonTypeName("DiscoverFacets")
public class RequestDiscoverFacets extends RequestAggregationBase {
    /**
     * When true, if the top results share a filter then restrict facet
     * discovery to that filter. Note that it attempts to discover category
     * based filters.
     */
    @JsonProperty(value = "discoverFilter")
    private Boolean discoverFilter;

    /**
     * When true, returns refinement values in the response.
     */
    @JsonProperty(value = "refinements")
    private Boolean refinements;

    /**
     * A list of facets to pin at the top positions of the DiscoveredFacets
     * aggregations list.
     */
    @JsonProperty(value = "pin")
    private List<RequestFacetBase> pin;

    /**
     * A list of facets to be included, but not necessarily at the top
     * positions.
     */
    @JsonProperty(value = "include")
    private List<RequestFacetBase> include;

    /**
     * A list of field names to exclude from consideration.
     */
    @JsonProperty(value = "exclude")
    private List<String> exclude;

    /**
     * default facets to apply.
     */
    @JsonProperty(value = "facetDefaults")
    private RequestFacet facetDefaults;

    /**
     * default range facets to apply.
     */
    @JsonProperty(value = "rangeFacetDefaults")
    private RequestRangeFacet rangeFacetDefaults;

    /**
     * Get when true, if the top results share a filter then restrict facet discovery to that filter. Note that it attempts to discover category based filters.
     *
     * @return the discoverFilter value
     */
    public Boolean discoverFilter() {
        return this.discoverFilter;
    }

    /**
     * Set when true, if the top results share a filter then restrict facet discovery to that filter. Note that it attempts to discover category based filters.
     *
     * @param discoverFilter the discoverFilter value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withDiscoverFilter(Boolean discoverFilter) {
        this.discoverFilter = discoverFilter;
        return this;
    }

    /**
     * Get when true, returns refinement values in the response.
     *
     * @return the refinements value
     */
    public Boolean refinements() {
        return this.refinements;
    }

    /**
     * Set when true, returns refinement values in the response.
     *
     * @param refinements the refinements value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withRefinements(Boolean refinements) {
        this.refinements = refinements;
        return this;
    }

    /**
     * Get a list of facets to pin at the top positions of the DiscoveredFacets aggregations list.
     *
     * @return the pin value
     */
    public List<RequestFacetBase> pin() {
        return this.pin;
    }

    /**
     * Set a list of facets to pin at the top positions of the DiscoveredFacets aggregations list.
     *
     * @param pin the pin value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withPin(List<RequestFacetBase> pin) {
        this.pin = pin;
        return this;
    }

    /**
     * Get a list of facets to be included, but not necessarily at the top positions.
     *
     * @return the include value
     */
    public List<RequestFacetBase> include() {
        return this.include;
    }

    /**
     * Set a list of facets to be included, but not necessarily at the top positions.
     *
     * @param include the include value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withInclude(List<RequestFacetBase> include) {
        this.include = include;
        return this;
    }

    /**
     * Get a list of field names to exclude from consideration.
     *
     * @return the exclude value
     */
    public List<String> exclude() {
        return this.exclude;
    }

    /**
     * Set a list of field names to exclude from consideration.
     *
     * @param exclude the exclude value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withExclude(List<String> exclude) {
        this.exclude = exclude;
        return this;
    }

    /**
     * Get default facets to apply.
     *
     * @return the facetDefaults value
     */
    public RequestFacet facetDefaults() {
        return this.facetDefaults;
    }

    /**
     * Set default facets to apply.
     *
     * @param facetDefaults the facetDefaults value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withFacetDefaults(RequestFacet facetDefaults) {
        this.facetDefaults = facetDefaults;
        return this;
    }

    /**
     * Get default range facets to apply.
     *
     * @return the rangeFacetDefaults value
     */
    public RequestRangeFacet rangeFacetDefaults() {
        return this.rangeFacetDefaults;
    }

    /**
     * Set default range facets to apply.
     *
     * @param rangeFacetDefaults the rangeFacetDefaults value to set
     * @return the RequestDiscoverFacets object itself.
     */
    public RequestDiscoverFacets withRangeFacetDefaults(RequestRangeFacet rangeFacetDefaults) {
        this.rangeFacetDefaults = rangeFacetDefaults;
        return this;
    }

}

