// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ResponseBingMatchingStream model.
 */
public class ResponseBingMatchingStream {
    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The score property.
     */
    @JsonProperty(value = "score")
    private Integer score;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the ResponseBingMatchingStream object itself.
     */
    public ResponseBingMatchingStream withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the score value.
     *
     * @return the score value
     */
    public Integer score() {
        return this.score;
    }

    /**
     * Set the score value.
     *
     * @param score the score value to set
     * @return the ResponseBingMatchingStream object itself.
     */
    public ResponseBingMatchingStream withScore(Integer score) {
        this.score = score;
        return this;
    }

}
