// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The abstract base type for a refinement on a facet.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseRefinementBase.class)
@JsonTypeName("Response.RefinementBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "NumberRefinement", value = ResponseNumberRefinement.class),
    @JsonSubTypes.Type(name = "StringRefinement", value = ResponseStringRefinement.class),
    @JsonSubTypes.Type(name = "BoolRefinement", value = ResponseBoolRefinement.class),
    @JsonSubTypes.Type(name = "RangeRefinement", value = ResponseRangeRefinement.class)
})
public class ResponseRefinementBase {
    /**
     * An estimate of the number of items in this refinement.
     */
    @JsonProperty(value = "estimatedCount")
    private Long estimatedCount;

    /**
     * Get an estimate of the number of items in this refinement.
     *
     * @return the estimatedCount value
     */
    public Long estimatedCount() {
        return this.estimatedCount;
    }

    /**
     * Set an estimate of the number of items in this refinement.
     *
     * @param estimatedCount the estimatedCount value to set
     * @return the ResponseRefinementBase object itself.
     */
    public ResponseRefinementBase withEstimatedCount(Long estimatedCount) {
        this.estimatedCount = estimatedCount;
        return this;
    }

}

