// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Defines a discrete number refinement on a numeric field.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseNumberRefinement.class)
@JsonTypeName("NumberRefinement")
public class ResponseNumberRefinement extends ResponseRefinementBase {
    /**
     * The actual filter value used to filter the list of items.
     */
    @JsonProperty(value = "value")
    private Double value;

    /**
     * Get the actual filter value used to filter the list of items.
     *
     * @return the value value
     */
    public Double value() {
        return this.value;
    }

    /**
     * Set the actual filter value used to filter the list of items.
     *
     * @param value the value value to set
     * @return the ResponseNumberRefinement object itself.
     */
    public ResponseNumberRefinement withValue(Double value) {
        this.value = value;
        return this;
    }

}

