// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The ResponseFacetBase model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "_type", defaultImpl = ResponseFacetBase.class)
@JsonTypeName("Response.FacetBase")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "NumberFacet", value = ResponseNumberFacet.class),
    @JsonSubTypes.Type(name = "StringFacet", value = ResponseStringFacet.class),
    @JsonSubTypes.Type(name = "CategoryFacet", value = ResponseCategoryFacet.class),
    @JsonSubTypes.Type(name = "BoolFacet", value = ResponseBoolFacet.class),
    @JsonSubTypes.Type(name = "RangeFacet", value = ResponseRangeFacet.class)
})
public class ResponseFacetBase extends ResponseFieldAggregationBase {
    /**
     * The facet label, that you can use to render your UI.
     */
    @JsonProperty(value = "label")
    private String label;

    /**
     * Get the facet label, that you can use to render your UI.
     *
     * @return the label value
     */
    public String label() {
        return this.label;
    }

    /**
     * Set the facet label, that you can use to render your UI.
     *
     * @param label the label value to set
     * @return the ResponseFacetBase object itself.
     */
    public ResponseFacetBase withLabel(String label) {
        this.label = label;
        return this;
    }

}

