/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Index model.
 */
public class Index {
    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The description property.
     */
    @JsonProperty(value = "description")
    private String description;

    /**
     * The regions property.
     */
    @JsonProperty(value = "regions")
    private List<Region> regions;

    /**
     * Possible values include: 'Unknown', 'Retail', 'Document', 'Hotel'.
     */
    @JsonProperty(value = "searchScenario")
    private String searchScenario;

    /**
     * The searchServices property.
     */
    @JsonProperty(value = "searchServices")
    private List<String> searchServices;

    /**
     * The schemaVersion property.
     */
    @JsonProperty(value = "schemaVersion")
    private String schemaVersion;

    /**
     * The fields property.
     */
    @JsonProperty(value = "fields")
    private List<IndexField> fields;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the Index object itself.
     */
    public Index withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the description value.
     *
     * @return the description value
     */
    public String description() {
        return this.description;
    }

    /**
     * Set the description value.
     *
     * @param description the description value to set
     * @return the Index object itself.
     */
    public Index withDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the regions value.
     *
     * @return the regions value
     */
    public List<Region> regions() {
        return this.regions;
    }

    /**
     * Set the regions value.
     *
     * @param regions the regions value to set
     * @return the Index object itself.
     */
    public Index withRegions(List<Region> regions) {
        this.regions = regions;
        return this;
    }

    /**
     * Get possible values include: 'Unknown', 'Retail', 'Document', 'Hotel'.
     *
     * @return the searchScenario value
     */
    public String searchScenario() {
        return this.searchScenario;
    }

    /**
     * Set possible values include: 'Unknown', 'Retail', 'Document', 'Hotel'.
     *
     * @param searchScenario the searchScenario value to set
     * @return the Index object itself.
     */
    public Index withSearchScenario(String searchScenario) {
        this.searchScenario = searchScenario;
        return this;
    }

    /**
     * Get the searchServices value.
     *
     * @return the searchServices value
     */
    public List<String> searchServices() {
        return this.searchServices;
    }

    /**
     * Set the searchServices value.
     *
     * @param searchServices the searchServices value to set
     * @return the Index object itself.
     */
    public Index withSearchServices(List<String> searchServices) {
        this.searchServices = searchServices;
        return this;
    }

    /**
     * Get the schemaVersion value.
     *
     * @return the schemaVersion value
     */
    public String schemaVersion() {
        return this.schemaVersion;
    }

    /**
     * Set the schemaVersion value.
     *
     * @param schemaVersion the schemaVersion value to set
     * @return the Index object itself.
     */
    public Index withSchemaVersion(String schemaVersion) {
        this.schemaVersion = schemaVersion;
        return this;
    }

    /**
     * Get the fields value.
     *
     * @return the fields value
     */
    public List<IndexField> fields() {
        return this.fields;
    }

    /**
     * Set the fields value.
     *
     * @param fields the fields value to set
     * @return the Index object itself.
     */
    public Index withFields(List<IndexField> fields) {
        this.fields = fields;
        return this;
    }

}
