/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The IndexField model.
 */
public class IndexField {
    /**
     * The name property.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * Possible values include: 'Unknown', 'String', 'Boolean', 'Number',
     * 'ProductId', 'DupId', 'StaticRank', 'Url', 'ImageUrl', 'Title',
     * 'Description', 'Category', 'Price', 'Rating', 'Brand', 'Model', 'Color',
     * 'Size', 'Material', 'Gender', 'AgeGroup', 'Array', 'Dictionary',
     * 'ExcludeFlag', 'Identifier', 'Object', 'DocumentId', 'Author',
     * 'CreatedAt', 'ModifiedAt', 'Paragraph', 'SubHeading', 'SectionHeader',
     * 'Address', 'RatingCount', 'ReviewCount', 'RatingScale', 'Amenities',
     * 'StreetAddress', 'Locality', 'SubRegion', 'AddressRegion', 'PostalCode',
     * 'PostOfficeBoxNumber', 'Country', 'CountryIso', 'Neighborhood',
     * 'OtherAreas', 'PhoneNumber', 'Barcode'.
     */
    @JsonProperty(value = "type")
    private IndexFieldType type;

    /**
     * The facetable property.
     */
    @JsonProperty(value = "facetable")
    private Boolean facetable;

    /**
     * The filterable property.
     */
    @JsonProperty(value = "filterable")
    private Boolean filterable;

    /**
     * The retrievable property.
     */
    @JsonProperty(value = "retrievable")
    private Boolean retrievable;

    /**
     * The searchable property.
     */
    @JsonProperty(value = "searchable")
    private Boolean searchable;

    /**
     * The sortable property.
     */
    @JsonProperty(value = "sortable")
    private Boolean sortable;

    /**
     * The fieldLabel property.
     */
    @JsonProperty(value = "fieldLabel")
    private String fieldLabel;

    /**
     * The fields property.
     */
    @JsonProperty(value = "fields")
    private List<IndexField> fields;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the IndexField object itself.
     */
    public IndexField withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get possible values include: 'Unknown', 'String', 'Boolean', 'Number', 'ProductId', 'DupId', 'StaticRank', 'Url', 'ImageUrl', 'Title', 'Description', 'Category', 'Price', 'Rating', 'Brand', 'Model', 'Color', 'Size', 'Material', 'Gender', 'AgeGroup', 'Array', 'Dictionary', 'ExcludeFlag', 'Identifier', 'Object', 'DocumentId', 'Author', 'CreatedAt', 'ModifiedAt', 'Paragraph', 'SubHeading', 'SectionHeader', 'Address', 'RatingCount', 'ReviewCount', 'RatingScale', 'Amenities', 'StreetAddress', 'Locality', 'SubRegion', 'AddressRegion', 'PostalCode', 'PostOfficeBoxNumber', 'Country', 'CountryIso', 'Neighborhood', 'OtherAreas', 'PhoneNumber', 'Barcode'.
     *
     * @return the type value
     */
    public IndexFieldType type() {
        return this.type;
    }

    /**
     * Set possible values include: 'Unknown', 'String', 'Boolean', 'Number', 'ProductId', 'DupId', 'StaticRank', 'Url', 'ImageUrl', 'Title', 'Description', 'Category', 'Price', 'Rating', 'Brand', 'Model', 'Color', 'Size', 'Material', 'Gender', 'AgeGroup', 'Array', 'Dictionary', 'ExcludeFlag', 'Identifier', 'Object', 'DocumentId', 'Author', 'CreatedAt', 'ModifiedAt', 'Paragraph', 'SubHeading', 'SectionHeader', 'Address', 'RatingCount', 'ReviewCount', 'RatingScale', 'Amenities', 'StreetAddress', 'Locality', 'SubRegion', 'AddressRegion', 'PostalCode', 'PostOfficeBoxNumber', 'Country', 'CountryIso', 'Neighborhood', 'OtherAreas', 'PhoneNumber', 'Barcode'.
     *
     * @param type the type value to set
     * @return the IndexField object itself.
     */
    public IndexField withType(IndexFieldType type) {
        this.type = type;
        return this;
    }

    /**
     * Get the facetable value.
     *
     * @return the facetable value
     */
    public Boolean facetable() {
        return this.facetable;
    }

    /**
     * Set the facetable value.
     *
     * @param facetable the facetable value to set
     * @return the IndexField object itself.
     */
    public IndexField withFacetable(Boolean facetable) {
        this.facetable = facetable;
        return this;
    }

    /**
     * Get the filterable value.
     *
     * @return the filterable value
     */
    public Boolean filterable() {
        return this.filterable;
    }

    /**
     * Set the filterable value.
     *
     * @param filterable the filterable value to set
     * @return the IndexField object itself.
     */
    public IndexField withFilterable(Boolean filterable) {
        this.filterable = filterable;
        return this;
    }

    /**
     * Get the retrievable value.
     *
     * @return the retrievable value
     */
    public Boolean retrievable() {
        return this.retrievable;
    }

    /**
     * Set the retrievable value.
     *
     * @param retrievable the retrievable value to set
     * @return the IndexField object itself.
     */
    public IndexField withRetrievable(Boolean retrievable) {
        this.retrievable = retrievable;
        return this;
    }

    /**
     * Get the searchable value.
     *
     * @return the searchable value
     */
    public Boolean searchable() {
        return this.searchable;
    }

    /**
     * Set the searchable value.
     *
     * @param searchable the searchable value to set
     * @return the IndexField object itself.
     */
    public IndexField withSearchable(Boolean searchable) {
        this.searchable = searchable;
        return this;
    }

    /**
     * Get the sortable value.
     *
     * @return the sortable value
     */
    public Boolean sortable() {
        return this.sortable;
    }

    /**
     * Set the sortable value.
     *
     * @param sortable the sortable value to set
     * @return the IndexField object itself.
     */
    public IndexField withSortable(Boolean sortable) {
        this.sortable = sortable;
        return this;
    }

    /**
     * Get the fieldLabel value.
     *
     * @return the fieldLabel value
     */
    public String fieldLabel() {
        return this.fieldLabel;
    }

    /**
     * Set the fieldLabel value.
     *
     * @param fieldLabel the fieldLabel value to set
     * @return the IndexField object itself.
     */
    public IndexField withFieldLabel(String fieldLabel) {
        this.fieldLabel = fieldLabel;
        return this;
    }

    /**
     * Get the fields value.
     *
     * @return the fields value
     */
    public List<IndexField> fields() {
        return this.fields;
    }

    /**
     * Set the fields value.
     *
     * @param fields the fields value to set
     * @return the IndexField object itself.
     */
    public IndexField withFields(List<IndexField> fields) {
        this.fields = fields;
        return this;
    }

}
