/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The IndexStatusResponse model.
 */
public class IndexStatusResponse {
    /**
     * The indexStatuses property.
     */
    @JsonProperty(value = "indexStatuses")
    private List<ResponseIndexStatus> indexStatuses;

    /**
     * Get the indexStatuses value.
     *
     * @return the indexStatuses value
     */
    public List<ResponseIndexStatus> indexStatuses() {
        return this.indexStatuses;
    }

    /**
     * Set the indexStatuses value.
     *
     * @param indexStatuses the indexStatuses value to set
     * @return the IndexStatusResponse object itself.
     */
    public IndexStatusResponse withIndexStatuses(List<ResponseIndexStatus> indexStatuses) {
        this.indexStatuses = indexStatuses;
        return this;
    }

}
