/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The IndexResponse model.
 */
public class IndexResponse {
    /**
     * The indexes property.
     */
    @JsonProperty(value = "indexes")
    private List<ResponseIndex> indexes;

    /**
     * Get the indexes value.
     *
     * @return the indexes value
     */
    public List<ResponseIndex> indexes() {
        return this.indexes;
    }

    /**
     * Set the indexes value.
     *
     * @param indexes the indexes value to set
     * @return the IndexResponse object itself.
     */
    public IndexResponse withIndexes(List<ResponseIndex> indexes) {
        this.indexes = indexes;
        return this;
    }

}
