/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The PushUpdateStatusResponse model.
 */
public class PushUpdateStatusResponse {
    /**
     * The updateId property.
     */
    @JsonProperty(value = "updateId")
    private String updateId;

    /**
     * Possible values include: 'InProgress', 'Succeeded',
     * 'PartiallySucceeded', 'Failed'.
     */
    @JsonProperty(value = "status")
    private String status;

    /**
     * The totalKeys property.
     */
    @JsonProperty(value = "totalKeys")
    private Integer totalKeys;

    /**
     * The successfulKeys property.
     */
    @JsonProperty(value = "successfulKeys")
    private Integer successfulKeys;

    /**
     * The failureMessages property.
     */
    @JsonProperty(value = "failureMessages")
    private List<String> failureMessages;

    /**
     * The records property.
     */
    @JsonProperty(value = "records")
    private List<ResponseRecordStatus> records;

    /**
     * Get the updateId value.
     *
     * @return the updateId value
     */
    public String updateId() {
        return this.updateId;
    }

    /**
     * Set the updateId value.
     *
     * @param updateId the updateId value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withUpdateId(String updateId) {
        this.updateId = updateId;
        return this;
    }

    /**
     * Get possible values include: 'InProgress', 'Succeeded', 'PartiallySucceeded', 'Failed'.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set possible values include: 'InProgress', 'Succeeded', 'PartiallySucceeded', 'Failed'.
     *
     * @param status the status value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get the totalKeys value.
     *
     * @return the totalKeys value
     */
    public Integer totalKeys() {
        return this.totalKeys;
    }

    /**
     * Set the totalKeys value.
     *
     * @param totalKeys the totalKeys value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withTotalKeys(Integer totalKeys) {
        this.totalKeys = totalKeys;
        return this;
    }

    /**
     * Get the successfulKeys value.
     *
     * @return the successfulKeys value
     */
    public Integer successfulKeys() {
        return this.successfulKeys;
    }

    /**
     * Set the successfulKeys value.
     *
     * @param successfulKeys the successfulKeys value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withSuccessfulKeys(Integer successfulKeys) {
        this.successfulKeys = successfulKeys;
        return this;
    }

    /**
     * Get the failureMessages value.
     *
     * @return the failureMessages value
     */
    public List<String> failureMessages() {
        return this.failureMessages;
    }

    /**
     * Set the failureMessages value.
     *
     * @param failureMessages the failureMessages value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withFailureMessages(List<String> failureMessages) {
        this.failureMessages = failureMessages;
        return this;
    }

    /**
     * Get the records value.
     *
     * @return the records value
     */
    public List<ResponseRecordStatus> records() {
        return this.records;
    }

    /**
     * Set the records value.
     *
     * @param records the records value to set
     * @return the PushUpdateStatusResponse object itself.
     */
    public PushUpdateStatusResponse withRecords(List<ResponseRecordStatus> records) {
        this.records = records;
        return this;
    }

}
