/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The PushDataUpdateResponse model.
 */
public class PushDataUpdateResponse {
    /**
     * The statuses property.
     */
    @JsonProperty(value = "statuses")
    private List<ResponsePushDataUpdateStatus> statuses;

    /**
     * The updateId property.
     */
    @JsonProperty(value = "updateId")
    private String updateId;

    /**
     * Get the statuses value.
     *
     * @return the statuses value
     */
    public List<ResponsePushDataUpdateStatus> statuses() {
        return this.statuses;
    }

    /**
     * Set the statuses value.
     *
     * @param statuses the statuses value to set
     * @return the PushDataUpdateResponse object itself.
     */
    public PushDataUpdateResponse withStatuses(List<ResponsePushDataUpdateStatus> statuses) {
        this.statuses = statuses;
        return this;
    }

    /**
     * Get the updateId value.
     *
     * @return the updateId value
     */
    public String updateId() {
        return this.updateId;
    }

    /**
     * Set the updateId value.
     *
     * @param updateId the updateId value to set
     * @return the PushDataUpdateResponse object itself.
     */
    public PushDataUpdateResponse withUpdateId(String updateId) {
        this.updateId = updateId;
        return this;
    }

}
