/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for Region.
 */
public enum Region {
    /** Enum value Unknown. */
    UNKNOWN("Unknown"),

    /** Enum value EastAsia. */
    EAST_ASIA("EastAsia"),

    /** Enum value EastUS2. */
    EAST_US2("EastUS2"),

    /** Enum value NorthCentralUS. */
    NORTH_CENTRAL_US("NorthCentralUS"),

    /** Enum value NorthEurope. */
    NORTH_EUROPE("NorthEurope"),

    /** Enum value WestUS2. */
    WEST_US2("WestUS2"),

    /** Enum value SoutheastAsia. */
    SOUTHEAST_ASIA("SoutheastAsia"),

    /** Enum value AustraliaEast. */
    AUSTRALIA_EAST("AustraliaEast"),

    /** Enum value AustraliaSoutheast. */
    AUSTRALIA_SOUTHEAST("AustraliaSoutheast"),

    /** Enum value AustraliaCentral. */
    AUSTRALIA_CENTRAL("AustraliaCentral"),

    /** Enum value AustraliaCentral2. */
    AUSTRALIA_CENTRAL2("AustraliaCentral2"),

    /** Enum value BrazilSouth. */
    BRAZIL_SOUTH("BrazilSouth"),

    /** Enum value CanadaCentral. */
    CANADA_CENTRAL("CanadaCentral"),

    /** Enum value CanadaEast. */
    CANADA_EAST("CanadaEast"),

    /** Enum value ChinaNorth. */
    CHINA_NORTH("ChinaNorth"),

    /** Enum value ChinaEast. */
    CHINA_EAST("ChinaEast"),

    /** Enum value ChinaNorth2. */
    CHINA_NORTH2("ChinaNorth2"),

    /** Enum value ChinaEast2. */
    CHINA_EAST2("ChinaEast2"),

    /** Enum value WestEurope. */
    WEST_EUROPE("WestEurope"),

    /** Enum value FranceCentral. */
    FRANCE_CENTRAL("FranceCentral"),

    /** Enum value FranceSouth. */
    FRANCE_SOUTH("FranceSouth"),

    /** Enum value GermanyCentral. */
    GERMANY_CENTRAL("GermanyCentral"),

    /** Enum value GermanyNortheast. */
    GERMANY_NORTHEAST("GermanyNortheast"),

    /** Enum value CentralIndia. */
    CENTRAL_INDIA("CentralIndia"),

    /** Enum value WestIndia. */
    WEST_INDIA("WestIndia"),

    /** Enum value SouthIndia. */
    SOUTH_INDIA("SouthIndia"),

    /** Enum value JapanEast. */
    JAPAN_EAST("JapanEast"),

    /** Enum value JapanWest. */
    JAPAN_WEST("JapanWest"),

    /** Enum value KoreaCentral. */
    KOREA_CENTRAL("KoreaCentral"),

    /** Enum value KoreaSouth. */
    KOREA_SOUTH("KoreaSouth"),

    /** Enum value EastUS. */
    EAST_US("EastUS"),

    /** Enum value WestUS. */
    WEST_US("WestUS"),

    /** Enum value CentralUS. */
    CENTRAL_US("CentralUS"),

    /** Enum value SouthCentralUS. */
    SOUTH_CENTRAL_US("SouthCentralUS"),

    /** Enum value WestCentralUS. */
    WEST_CENTRAL_US("WestCentralUS"),

    /** Enum value SouthAfricaNorth. */
    SOUTH_AFRICA_NORTH("SouthAfricaNorth"),

    /** Enum value SouthAfricaWest. */
    SOUTH_AFRICA_WEST("SouthAfricaWest"),

    /** Enum value UKWest. */
    UKWEST("UKWest"),

    /** Enum value UKSouth. */
    UKSOUTH("UKSouth"),

    /** Enum value UAENorth. */
    UAENORTH("UAENorth"),

    /** Enum value UAECentral. */
    UAECENTRAL("UAECentral");

    /** The actual serialized value for a Region instance. */
    private String value;

    Region(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a Region instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed Region object, or null if unable to parse.
     */
    @JsonCreator
    public static Region fromString(String value) {
        Region[] items = Region.values();
        for (Region item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
