/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ResponsePushDataUpdateStatus model.
 */
public class ResponsePushDataUpdateStatus {
    /**
     * The key property.
     */
    @JsonProperty(value = "key")
    private String key;

    /**
     * Possible values include: 'Queued', 'Error'.
     */
    @JsonProperty(value = "status")
    private ResponsePushStatus status;

    /**
     * The errorMessage property.
     */
    @JsonProperty(value = "errorMessage")
    private String errorMessage;

    /**
     * Get the key value.
     *
     * @return the key value
     */
    public String key() {
        return this.key;
    }

    /**
     * Set the key value.
     *
     * @param key the key value to set
     * @return the ResponsePushDataUpdateStatus object itself.
     */
    public ResponsePushDataUpdateStatus withKey(String key) {
        this.key = key;
        return this;
    }

    /**
     * Get possible values include: 'Queued', 'Error'.
     *
     * @return the status value
     */
    public ResponsePushStatus status() {
        return this.status;
    }

    /**
     * Set possible values include: 'Queued', 'Error'.
     *
     * @param status the status value to set
     * @return the ResponsePushDataUpdateStatus object itself.
     */
    public ResponsePushDataUpdateStatus withStatus(ResponsePushStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Get the errorMessage value.
     *
     * @return the errorMessage value
     */
    public String errorMessage() {
        return this.errorMessage;
    }

    /**
     * Set the errorMessage value.
     *
     * @param errorMessage the errorMessage value to set
     * @return the ResponsePushDataUpdateStatus object itself.
     */
    public ResponsePushDataUpdateStatus withErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

}
