/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ResponseRecordStatus model.
 */
public class ResponseRecordStatus {
    /**
     * The recordId property.
     */
    @JsonProperty(value = "recordId")
    private String recordId;

    /**
     * Possible values include: 'InProgress', 'Succeeded',
     * 'PartiallySucceeded', 'Failed'.
     */
    @JsonProperty(value = "status")
    private String status;

    /**
     * The errorMessage property.
     */
    @JsonProperty(value = "errorMessage")
    private String errorMessage;

    /**
     * Get the recordId value.
     *
     * @return the recordId value
     */
    public String recordId() {
        return this.recordId;
    }

    /**
     * Set the recordId value.
     *
     * @param recordId the recordId value to set
     * @return the ResponseRecordStatus object itself.
     */
    public ResponseRecordStatus withRecordId(String recordId) {
        this.recordId = recordId;
        return this;
    }

    /**
     * Get possible values include: 'InProgress', 'Succeeded', 'PartiallySucceeded', 'Failed'.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set possible values include: 'InProgress', 'Succeeded', 'PartiallySucceeded', 'Failed'.
     *
     * @param status the status value to set
     * @return the ResponseRecordStatus object itself.
     */
    public ResponseRecordStatus withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get the errorMessage value.
     *
     * @return the errorMessage value
     */
    public String errorMessage() {
        return this.errorMessage;
    }

    /**
     * Set the errorMessage value.
     *
     * @param errorMessage the errorMessage value to set
     * @return the ResponseRecordStatus object itself.
     */
    public ResponseRecordStatus withErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

}
