/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ResponseIndex model.
 */
public class ResponseIndex extends Index {
    /**
     * The id property.
     */
    @JsonProperty(value = "id")
    private String id;

    /**
     * Possible values include: 'Unknown', 'NotStarted', 'Provisioning',
     * 'Deprovisioning', 'Succeeded', 'Failed'.
     */
    @JsonProperty(value = "provisioningState")
    private String provisioningState;

    /**
     * The createdDateTime property.
     */
    @JsonProperty(value = "createdDateTime")
    private String createdDateTime;

    /**
     * Get the id value.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Set the id value.
     *
     * @param id the id value to set
     * @return the ResponseIndex object itself.
     */
    public ResponseIndex withId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get possible values include: 'Unknown', 'NotStarted', 'Provisioning', 'Deprovisioning', 'Succeeded', 'Failed'.
     *
     * @return the provisioningState value
     */
    public String provisioningState() {
        return this.provisioningState;
    }

    /**
     * Set possible values include: 'Unknown', 'NotStarted', 'Provisioning', 'Deprovisioning', 'Succeeded', 'Failed'.
     *
     * @param provisioningState the provisioningState value to set
     * @return the ResponseIndex object itself.
     */
    public ResponseIndex withProvisioningState(String provisioningState) {
        this.provisioningState = provisioningState;
        return this;
    }

    /**
     * Get the createdDateTime value.
     *
     * @return the createdDateTime value
     */
    public String createdDateTime() {
        return this.createdDateTime;
    }

    /**
     * Set the createdDateTime value.
     *
     * @param createdDateTime the createdDateTime value to set
     * @return the ResponseIndex object itself.
     */
    public ResponseIndex withCreatedDateTime(String createdDateTime) {
        this.createdDateTime = createdDateTime;
        return this;
    }

}
