/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The TransformationConfigResponse model.
 */
public class TransformationConfigResponse {
    /**
     * The value property.
     */
    @JsonProperty(value = "value")
    private String value;

    /**
     * The tryOutId property.
     */
    @JsonProperty(value = "tryOutId")
    private String tryOutId;

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public String value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the TransformationConfigResponse object itself.
     */
    public TransformationConfigResponse withValue(String value) {
        this.value = value;
        return this;
    }

    /**
     * Get the tryOutId value.
     *
     * @return the tryOutId value
     */
    public String tryOutId() {
        return this.tryOutId;
    }

    /**
     * Set the tryOutId value.
     *
     * @param tryOutId the tryOutId value to set
     * @return the TransformationConfigResponse object itself.
     */
    public TransformationConfigResponse withTryOutId(String tryOutId) {
        this.tryOutId = tryOutId;
        return this;
    }

}
