/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.ecommerce.ingestion.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The TransformationTryoutResponse model.
 */
public class TransformationTryoutResponse {
    /**
     * The status property.
     */
    @JsonProperty(value = "status")
    private String status;

    /**
     * The errorMessage property.
     */
    @JsonProperty(value = "errorMessage")
    private String errorMessage;

    /**
     * The results property.
     */
    @JsonProperty(value = "results")
    private List<String> results;

    /**
     * The consoleOutput property.
     */
    @JsonProperty(value = "consoleOutput")
    private List<String> consoleOutput;

    /**
     * Get the status value.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Set the status value.
     *
     * @param status the status value to set
     * @return the TransformationTryoutResponse object itself.
     */
    public TransformationTryoutResponse withStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Get the errorMessage value.
     *
     * @return the errorMessage value
     */
    public String errorMessage() {
        return this.errorMessage;
    }

    /**
     * Set the errorMessage value.
     *
     * @param errorMessage the errorMessage value to set
     * @return the TransformationTryoutResponse object itself.
     */
    public TransformationTryoutResponse withErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
        return this;
    }

    /**
     * Get the results value.
     *
     * @return the results value
     */
    public List<String> results() {
        return this.results;
    }

    /**
     * Set the results value.
     *
     * @param results the results value to set
     * @return the TransformationTryoutResponse object itself.
     */
    public TransformationTryoutResponse withResults(List<String> results) {
        this.results = results;
        return this;
    }

    /**
     * Get the consoleOutput value.
     *
     * @return the consoleOutput value
     */
    public List<String> consoleOutput() {
        return this.consoleOutput;
    }

    /**
     * Set the consoleOutput value.
     *
     * @param consoleOutput the consoleOutput value to set
     * @return the TransformationTryoutResponse object itself.
     */
    public TransformationTryoutResponse withConsoleOutput(List<String> consoleOutput) {
        this.consoleOutput = consoleOutput;
        return this;
    }

}
