// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.ingestion.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A response that represents a query to an index status within a region.
 */
public class ResponseIndexStatus {
    /**
     * Possible values include: 'Unknown', 'EastAsia', 'EastUS2',
     * 'NorthCentralUS', 'NorthEurope', 'WestUS2', 'SoutheastAsia',
     * 'AustraliaEast', 'AustraliaSoutheast', 'AustraliaCentral',
     * 'AustraliaCentral2', 'BrazilSouth', 'CanadaCentral', 'CanadaEast',
     * 'ChinaNorth', 'ChinaEast', 'ChinaNorth2', 'ChinaEast2', 'WestEurope',
     * 'FranceCentral', 'FranceSouth', 'GermanyCentral', 'GermanyNortheast',
     * 'CentralIndia', 'WestIndia', 'SouthIndia', 'JapanEast', 'JapanWest',
     * 'KoreaCentral', 'KoreaSouth', 'EastUS', 'WestUS', 'CentralUS',
     * 'SouthCentralUS', 'WestCentralUS', 'SouthAfricaNorth',
     * 'SouthAfricaWest', 'UKWest', 'UKSouth', 'UAENorth', 'UAECentral'.
     */
    @JsonProperty(value = "region")
    private Region region;

    /**
     * The provisioning state for the index within the specified region.
     * Possible values include: 'Unknown', 'NotStarted', 'Provisioning',
     * 'Deprovisioning', 'Succeeded', 'Failed'.
     */
    @JsonProperty(value = "provisioningState")
    private String provisioningState;

    /**
     * The percentage of provisioning for the index withing the region.
     */
    @JsonProperty(value = "provisioningPercentage")
    private Double provisioningPercentage;

    /**
     * Get possible values include: 'Unknown', 'EastAsia', 'EastUS2', 'NorthCentralUS', 'NorthEurope', 'WestUS2', 'SoutheastAsia', 'AustraliaEast', 'AustraliaSoutheast', 'AustraliaCentral', 'AustraliaCentral2', 'BrazilSouth', 'CanadaCentral', 'CanadaEast', 'ChinaNorth', 'ChinaEast', 'ChinaNorth2', 'ChinaEast2', 'WestEurope', 'FranceCentral', 'FranceSouth', 'GermanyCentral', 'GermanyNortheast', 'CentralIndia', 'WestIndia', 'SouthIndia', 'JapanEast', 'JapanWest', 'KoreaCentral', 'KoreaSouth', 'EastUS', 'WestUS', 'CentralUS', 'SouthCentralUS', 'WestCentralUS', 'SouthAfricaNorth', 'SouthAfricaWest', 'UKWest', 'UKSouth', 'UAENorth', 'UAECentral'.
     *
     * @return the region value
     */
    public Region region() {
        return this.region;
    }

    /**
     * Set possible values include: 'Unknown', 'EastAsia', 'EastUS2', 'NorthCentralUS', 'NorthEurope', 'WestUS2', 'SoutheastAsia', 'AustraliaEast', 'AustraliaSoutheast', 'AustraliaCentral', 'AustraliaCentral2', 'BrazilSouth', 'CanadaCentral', 'CanadaEast', 'ChinaNorth', 'ChinaEast', 'ChinaNorth2', 'ChinaEast2', 'WestEurope', 'FranceCentral', 'FranceSouth', 'GermanyCentral', 'GermanyNortheast', 'CentralIndia', 'WestIndia', 'SouthIndia', 'JapanEast', 'JapanWest', 'KoreaCentral', 'KoreaSouth', 'EastUS', 'WestUS', 'CentralUS', 'SouthCentralUS', 'WestCentralUS', 'SouthAfricaNorth', 'SouthAfricaWest', 'UKWest', 'UKSouth', 'UAENorth', 'UAECentral'.
     *
     * @param region the region value to set
     * @return the ResponseIndexStatus object itself.
     */
    public ResponseIndexStatus withRegion(Region region) {
        this.region = region;
        return this;
    }

    /**
     * Get the provisioning state for the index within the specified region. Possible values include: 'Unknown', 'NotStarted', 'Provisioning', 'Deprovisioning', 'Succeeded', 'Failed'.
     *
     * @return the provisioningState value
     */
    public String provisioningState() {
        return this.provisioningState;
    }

    /**
     * Set the provisioning state for the index within the specified region. Possible values include: 'Unknown', 'NotStarted', 'Provisioning', 'Deprovisioning', 'Succeeded', 'Failed'.
     *
     * @param provisioningState the provisioningState value to set
     * @return the ResponseIndexStatus object itself.
     */
    public ResponseIndexStatus withProvisioningState(String provisioningState) {
        this.provisioningState = provisioningState;
        return this;
    }

    /**
     * Get the percentage of provisioning for the index withing the region.
     *
     * @return the provisioningPercentage value
     */
    public Double provisioningPercentage() {
        return this.provisioningPercentage;
    }

    /**
     * Set the percentage of provisioning for the index withing the region.
     *
     * @param provisioningPercentage the provisioningPercentage value to set
     * @return the ResponseIndexStatus object itself.
     */
    public ResponseIndexStatus withProvisioningPercentage(Double provisioningPercentage) {
        this.provisioningPercentage = provisioningPercentage;
        return this;
    }

}
