// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.bing.commerce.search;

import com.microsoft.rest.RestClient;

/**
 * The interface for BingCommerceSearch class.
 */
public interface BingCommerceSearch {
    /**
     * Gets the REST client.
     *
     * @return the {@link RestClient} object.
    */
    RestClient restClient();

    /**
     * The default base URL.
     */
    String DEFAULT_BASE_URL = "https://commerce.bing.com/api/search/v1";

    /**
     * Gets the Searchs object to access its operations.
     * @return the Searchs object.
     */
    Searchs searchs();

}
